# -*- coding: utf-8 -*-
"""Abused.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfiXYUvfCslfbJeiHehCocGMPOWPsZNp

#**Table**

1.   Section 0 : Imports and common functions
2.   Section 1: Data Loading
3.   Section 2: Text Cleaning
4.   Section 3: Bertopic
5.   Section 4: exluding class other cyberbullying
6.   Section 5: preprocessing and splitting
7.   Section 6: EDA
8.   Section 7: Oversampling and Loading
9.   Section 8: Baseline model
10.  Section 9: TF-IDF + Logistic Regression
11.  Section 10: TF-IDF + XGBoost
12.  Section 11: Utilities
13.  Section 12: Text CNN
14.  Section 13: BiLSTM + Attention
15.  Section 14: GloVe CNN
16.  Section 15: GloVe BiLSTM
17.  Section 16: BERT
18.  Section 17: Results and interpretation

#Section 0 : Imports and common functions
"""

!pip install -q gensim emoji contractions langdetect

from pathlib import Path

Path("models").mkdir(exist_ok=True)

# ── 0.1 Imports ─────────────────────────────────────────────────────────────
import os, sys, json, time, warnings, logging
import random
from pathlib import Path
from datetime import datetime
from collections import Counter

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm

# Sklearn
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import (
    StratifiedKFold, train_test_split, cross_val_score
)
from sklearn.metrics import (
    classification_report, confusion_matrix,
    f1_score, accuracy_score, roc_auc_score
)
from sklearn.preprocessing import LabelEncoder
import joblib

# XGBoost
from xgboost import XGBClassifier

# Deep learning
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from torch.optim import AdamW
from torch.optim.lr_scheduler import ReduceLROnPlateau

# Transformers
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments, Trainer,
    EarlyStoppingCallback
)
from transformers.trainer_utils import get_last_checkpoint

# Embeddings
import gensim.downloader as api

# NLP
import nltk
import re, unicodedata
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download(["stopwords", "wordnet", "punkt"], quiet=True)

warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.INFO)
print("Imports OK")

# ── 0.2 Global Configuration ─────────────────────────────────────────────────
CFG = {
    # ── Reproducibility
    "seed": 42,

    # ── Paths
    "data_dir":   Path("data/"),
    "output_dir": Path("outputs/"),
    "model_dir":  Path("models/"),
    "log_dir":    Path("logs/"),

    # ── Task  ← CHANGE ONLY THIS BLOCK between notebooks
    # Options: sentiment_analysis | abuse_detection | (any classification task)
    "task":       "abuse_detection",
    "text_col":   "text",
    "label_col":  "target",
    "num_labels": 3,

    # ── Split
    "test_size": 0.15,
    "val_size":  0.15,

    # ── Cross-validation
    "use_cv":   True,
    "cv_folds": 5,

    # ── TF-IDF
    "tfidf_word_ngrams": (1, 2),
    "use_char_ngrams":   True,
    "class_weight":      "balanced",

    # ── Embeddings
    "embedding_model": "glove-wiki-gigaword-100",  # or "fasttext-wiki-news-subwords-300"
    "embedding_dim":   100,
    "vocab_size":      30_000,
    "max_seq_len":     128,
    "pad_token":       "<PAD>",
    "unk_token":       "<UNK>",

    # ── Deep learning (CNN / BiLSTM / MLP)
    "dl_batch_size": 64,
    "dl_epochs":     20,
    "dl_lr":         1e-3,
    "dl_patience":   3,
    "dropout":       0.3,

    # ── CNN-specific
    "cnn_num_filters":  128,
    "cnn_kernel_sizes": [2, 3, 4],

    # ── BiLSTM-specific
    "lstm_hidden_dim": 128,
    "lstm_num_layers": 2,

    # ── Transformer
    "trf_model":  "bert-base-uncased",
    "max_len":    256,
    "batch_size": 16,
    "epochs":     5,
    "lr":         2e-5,

    # ── Device
    "device": (
        "mps"  if torch.backends.mps.is_available() and torch.backends.mps.is_built()
        else "cuda" if torch.cuda.is_available()
        else "cpu"
    )
}

#Create directories (uncomment to create folders)
for d in ["data_dir", "output_dir", "model_dir", "log_dir"]:
    CFG[d].mkdir(parents=True, exist_ok=True)

print(f"Task  : {CFG['task']}")
print(f"Labels: {CFG['num_labels']}")
print(f"Device: {CFG['device']}")

def set_seed(seed: int = 42):
    """Fix all random seeds for full reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

set_seed(CFG["seed"])
print("Seed set.")

"""# Section 1: Data Loading"""

from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/MAGO/CyberBulling_Classification/cyberbullying_tweets.csv"

df_raw = pd.read_csv(path)
df_raw.head()

df_raw = pd.read_csv(path)
label_counts = df_raw['cyberbullying_type'].value_counts()
print(label_counts)

# Calcola la lunghezza del testo in numero di parole
df_raw['text_len'] = df_raw['tweet_text'].str.split().apply(len)

"""# Section 2 : Text Cleaning"""

# remove links , mentions and new line characters, emojis
# # Clean hashtags at the end of the sentence, and keep those in the middle of the sentence by removing just the # symbol
import re
import string
import emoji
import contractions
from langdetect import detect, LangDetectException

# Rimuove emoji
def strip_emoji(text):
    return emoji.replace_emoji(text, replace='')

# Rimuove punteggiatura, links, mentions, newline, ma mantiene stopwords
def strip_all_entities(text):
    text = re.sub(r'\r|\n', ' ', text.lower())  # lowercase + newline
    text = re.sub(r"(?:\@|https?\://)\S+", "", text)  # mentions e link
    text = re.sub(r'[^\x00-\x7f]', '', text)  # non-ASCII
    banned_list = string.punctuation
    table = str.maketrans('', '', banned_list)
    text = text.translate(table)
    return text

# Pulizia hashtag
def clean_hashtags(tweet):
    # Rimuove hashtag alla fine
    new_tweet = re.sub(r'(\s+#[[\w-]+)+s*$', '', tweet).strip()
    # Rimuove solo # all'interno della frase
    new_tweet = re.sub(r'#([\w-]+)', r'\1', new_tweet).strip()
    return new_tweet

# Filtra caratteri speciali come & e $
def filter_chars(text):
    return ' '.join('' if ('$' in word) or ('&' in word) else word for word in text.split())

# Rimuove spazi multipli
def remove_mult_spaces(text):
    return re.sub(r"\s\s+", " ", text)

# Tiene solo testi in inglese
def filter_non_english(text):
    try:
        lang = detect(text)
    except LangDetectException:
        lang = "unknown"
    return text if lang == "en" else ""

# Espande contrazioni
def expand_contractions(text):
    return contractions.fix(text)

# Rimuove numeri
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

# Rimuove parole troppo corte
def remove_short_words(text, min_len=2):
    words = text.split()
    long_words = [word for word in words if len(word) >= min_len]
    return ' '.join(long_words)

# Sostituisce parole allungate
def replace_elongated_words(text):
    regex_pattern = r'\b(\w+)((\w)\3{2,})(\w*)\b'
    return re.sub(regex_pattern, r'\1\3\4', text)

# Rimuove punteggiatura ripetuta
def remove_repeated_punctuation(text):
    return re.sub(r'[\?\.\!]+(?=[\?\.\!])', '', text)

# Rimuove spazi extra
def remove_extra_whitespace(text):
    return ' '.join(text.split())

# Rimuove short URLs comuni
def remove_url_shorteners(text):
    return re.sub(r'(?:http[s]?://)?(?:www\.)?(?:bit\.ly|goo\.gl|t\.co|tinyurl\.com|tr\.im|is\.gd|cli\.gs|u\.nu|url\.ie|tiny\.cc|alturl\.com|ow\.ly|bit\.do|adoro\.to)\S+', '', text)

# Strip spazi iniziali/finali
def remove_spaces_tweets(tweet):
    return tweet.strip()

# Rimuove tweet troppo corti (<3 parole)
def remove_short_tweets(tweet, min_words=3):
    words = tweet.split()
    return tweet if len(words) >= min_words else ""

# Funzione principale di cleaning
def clean_tweet(tweet):
    tweet = strip_emoji(tweet)
    tweet = expand_contractions(tweet)
    tweet = filter_non_english(tweet)
    tweet = strip_all_entities(tweet)
    tweet = clean_hashtags(tweet)
    tweet = filter_chars(tweet)
    tweet = remove_mult_spaces(tweet)
    tweet = remove_numbers(tweet)
    tweet = remove_short_words(tweet)
    tweet = replace_elongated_words(tweet)
    tweet = remove_repeated_punctuation(tweet)
    tweet = remove_extra_whitespace(tweet)
    tweet = remove_url_shorteners(tweet)
    tweet = remove_spaces_tweets(tweet)
    tweet = remove_short_tweets(tweet)
    tweet = ' '.join(tweet.split())
    return tweet

# new column with cleaned text
df_raw['clean_text'] = df_raw['tweet_text'].apply(clean_tweet)

df_raw[['tweet_text', 'clean_text']].head(10)

# Removes duplicates, keeps first occurrence
df_raw = df_raw.drop_duplicates(subset='clean_text', keep='first').reset_index(drop=True)

# shows how many clean tweets are duplicates
print(df_raw['clean_text'].duplicated().sum())

print(df_raw.shape)
print(df_raw.head(10))

class_counts = df_raw['cyberbullying_type'].value_counts()
print(class_counts)

class_percent = df_raw['cyberbullying_type'].value_counts(normalize=True) * 100
print(class_percent)

"""# Section 3: BERTOPIC"""

# Clean
df_raw["clean_text"] = df_raw["tweet_text"].apply(clean_tweet)

# Remove duplicates
df_raw = df_raw.drop_duplicates(subset="clean_text", keep="first").reset_index(drop=True)

# Ora estrai other
df_other = df_raw[df_raw["cyberbullying_type"] == "other_cyberbullying"].copy()

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

documents = df_other["clean_text"].tolist()

# Pre-compute embeddings
embeddings = embedding_model.encode(
    documents,
    show_progress_bar=True
)

from umap import UMAP

umap_model = UMAP(
    n_neighbors=15,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
    random_state=42
)

from hdbscan import HDBSCAN

hdbscan_model = HDBSCAN(
    min_cluster_size=80,
    min_samples=10,
    metric="euclidean",
    cluster_selection_method="eom",
    prediction_data=True
)

from sklearn.feature_extraction.text import CountVectorizer

vectorizer_model = CountVectorizer(
    ngram_range=(1, 2),
    stop_words="english",
    min_df=5,
    max_df=0.9
)

# ── BERTopic
!pip install bertopic --quiet

from bertopic import BERTopic

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    calculate_probabilities=True,
    verbose=True
)

topics, probs = topic_model.fit_transform(documents, embeddings)

print(f"Number of topics: {len(set(topics)) - 1}")
print(f"Outliers: {topics.count(-1)} ({100*topics.count(-1)/len(topics):.1f}%)")

topic_model.get_topic_info().head(10)

topic_model.get_topic(0)

representative_docs = topic_model.get_representative_docs()

for i, doc in enumerate(representative_docs[0][:3]):
    print(f"Doc {i+1}: {doc[:300]}\n")

print(f"Outliers before: {topics.count(-1)}")

new_topics = topic_model.reduce_outliers(
    documents,
    topics,
    strategy="embeddings"
)

print(f"Outliers after: {list(new_topics).count(-1)}")

"""# BERTOPIC results"""

topic_model.visualize_documents(documents)

topic_model.visualize_topics()

topic_model.visualize_hierarchy()

new_topics = topic_model.reduce_outliers(documents, topics, strategy="embeddings")
print("Outliers after:", list(new_topics).count(-1))

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Ottieni embeddings dei topic (usati da BERTopic per rappresentare i topic)
topic_embeddings = topic_model.topic_embeddings_

# Calcola matrice di similarità coseno tra tutti i topic
similarity_matrix = cosine_similarity(topic_embeddings)

# Escludi outlier (-1)
topic_ids = [t for t in topic_model.get_topic_info()["Topic"] if t != -1]

# Creiamo lista di coppie simili sopra una soglia (es. 0.75)
threshold = 0.75
similar_pairs = []

for i, tid1 in enumerate(topic_ids):
    for j, tid2 in enumerate(topic_ids):
        if i < j and similarity_matrix[tid1, tid2] >= threshold:
            similar_pairs.append((tid1, tid2))

print("Topic pairs with similarity >= 0.75:", similar_pairs)

topics_to_merge = [[0, 2, 4]]


topic_model.merge_topics(documents, topics_to_merge)


topics, probs = topic_model.fit_transform(documents)


topics = topic_model.reduce_outliers(documents, topics, strategy="embeddings")

topic_info = topic_model.get_topic_info()
print(topic_info)


rep_docs = topic_model.get_representative_docs()

active_topic_ids = sorted([topic_id for topic_id in rep_docs.keys() if topic_id != -1])


for i, topic_id in enumerate(active_topic_ids[:5]):
    docs_for_topic = rep_docs[topic_id]
    print(f"\nTopic {topic_id} - first 3 representative docs:")
    for doc in docs_for_topic[:3]:
        print(" ", doc[:200], "...")

import matplotlib.pyplot as plt
from wordcloud import WordCloud


fig_hierarchy = topic_model.visualize_hierarchy()
fig_hierarchy.show()


fig_similarity = topic_model.visualize_topics()
fig_similarity.show()


fig_freq = topic_model.visualize_barchart(top_n_topics=15)
fig_freq.show()



topic_freq = topic_model.get_topic_freq()
topic_freq.plot(kind='bar', x='Topic', y='Count', figsize=(12,6), legend=False)
plt.title("Topic Frequencies")
plt.xlabel("Topic ID")
plt.ylabel("Number of Documents")
plt.show()

total_docs = len(documents)


topic_freq = topic_model.get_topic_freq()
topic_freq['Percentage'] = 100 * topic_freq['Count'] / total_docs


top_words = []
for topic_id in topic_freq['Topic']:
    if topic_id == -1:
        top_words.append(["-"])
    else:
        words = [w for w, _ in topic_model.get_topic(topic_id)[:10]]
        top_words.append(words)

topic_freq['Top_Words'] = top_words

topic_freq_sorted = topic_freq.sort_values(by='Count', ascending=False).reset_index(drop=True)
topic_freq_sorted.head(15)

"""#Section 4: exluding class other cyberbullying"""

df = df_raw[df_raw["cyberbullying_type"] != "other_cyberbullying"]

df["cyberbullying_type"].value_counts()

"""# Section 5: Preprocessing and Splitting"""

# ── 2.1 Preprocessing Functions ──────────────────────────────────────────────
STOP = set(stopwords.words("english"))  # [TASK-SPECIFIC] change language if needed
lemmatizer = WordNetLemmatizer()

def normalize_text(text: str) -> str:
    """
    Minimal cleaning — used as input for Transformers.
    Keeps punctuation and casing information the subword tokenizer relies on.
    """
    text = str(text).lower()
    text = unicodedata.normalize("NFKD", text)
    text = re.sub(r"http\S+|www\S+", " ", text)          # URLs
    text = re.sub(r"@\w+|#\w+", " ", text)                # mentions / hashtags
    text = re.sub(r"[^a-zA-Z0-9\s!?.,\'\']", " ", text)   # special chars
    text = re.sub(r"\s+", " ", text).strip()
    return text


def preprocess(text: str,
               remove_stopwords: bool = True,
               lemmatize: bool = True) -> str:
    """
    Full cleaning — used for classical ML and embedding-based models.
    Applies stopword removal and lemmatization on top of normalize_text.
    """
    text   = normalize_text(text)
    tokens = text.split()
    if remove_stopwords:
        tokens = [t for t in tokens if t not in STOP]
    if lemmatize:
        tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return " ".join(tokens)


# Smoke test
sample = "This is a GREAT movie!! http://example.com @user #review"
print("Raw         :", sample)
print("Normalized  :", normalize_text(sample))
print("Preprocessed:", preprocess(sample))

from sklearn.preprocessing import LabelEncoder
from tqdm import tqdm


CFG = {
    "text_col": "tweet_text",
    "label_col": "cyberbullying_type",
    "task": "Cyberbullying Classification"
}



# Preprocessing
tqdm.pandas(desc="Preprocessing")
df["text_clean"] = df[CFG["text_col"]].progress_apply(preprocess)     # full cleaning per ML/CNN/RNN
df["text_raw"]   = df[CFG["text_col"]].progress_apply(normalize_text) # minimal cleaning per Transformers

# Drop missing / duplicate
df = df.dropna(subset=[CFG["text_col"], CFG["label_col"]])
df = df.drop_duplicates(subset=[CFG["text_col"]])
print(f"Final dataset size: {len(df)}")

# Encode Labels
le = LabelEncoder()
df["label_enc"] = le.fit_transform(df[CFG["label_col"]])
print("Class mapping:", dict(zip(le.classes_, le.transform(le.classes_))))

df.head(1)

topic_info = topic_model.get_topic_info()
active_topic_ids = topic_info[topic_info.Topic != -1]['Topic'].tolist()

for i in active_topic_ids:
    topic_words = topic_model.get_topic(i)
    # Ensure topic_words is a list before subscripting
    if isinstance(topic_words, list):
        print(f"Topic {i}: {topic_words[:10]}")  # prime 10 parole
    else:
        print(f"Topic {i}: Unexpected return type from get_topic - {type(topic_words)}")

# ── 3.1 Stratified Split ──────────────────────────────────────────────────────

CFG["test_size"] = 0.15
CFG["val_size"] = 0.15
CFG["seed"] = 42
CFG["cv_folds"] = 5

df_train_full, df_test = train_test_split(
    df,
    test_size=CFG["test_size"],
    random_state=CFG["seed"],
    stratify=df["label_enc"],
)

df_train, df_val = train_test_split(
    df_train_full,
    test_size=CFG["val_size"] / (1 - CFG["test_size"]),
    random_state=CFG["seed"],
    stratify=df_train_full["label_enc"],
)

# Reset indices — important for DataLoader alignment
df_train = df_train.reset_index(drop=True)
df_val   = df_val.reset_index(drop=True)
df_test  = df_test.reset_index(drop=True)

print(f"Train: {len(df_train)} | Val: {len(df_val)} | Test: {len(df_test)}")

# ── 3.2 Shared Arrays ────────────────────────────────────────────────────────
# Classical ML & CNN/RNN → preprocessed text
X_train = df_train["text_clean"].values
X_val   = df_val["text_clean"].values
X_test  = df_test["text_clean"].values

# Transformers → minimally cleaned text
X_train_raw = df_train["text_raw"].values
X_val_raw   = df_val["text_raw"].values
X_test_raw  = df_test["text_raw"].values

y_train = df_train["label_enc"].values
y_val   = df_val["label_enc"].values
y_test  = df_test["label_enc"].values

# ── 3.3 Cross-Validation Object ──────────────────────────────────────────────
cv = StratifiedKFold(
    n_splits=CFG["cv_folds"],
    shuffle=True,
    random_state=CFG["seed"]
)

"""# Section 6: EDA"""

print("Missing values:\n", df_raw.isnull().sum())
print("\nDuplicated rows:", df_raw.duplicated().sum())


print("\nEmpty texts:", (df_raw["tweet_text"].str.strip() == "").sum())

df_raw["text_len"].describe()

from collections import Counter

all_words = " ".join(df_raw["tweet_text"]).lower().split()
common_words = Counter(all_words).most_common(20)

print(common_words)

sns.boxplot(
    data=df_raw,
    x="cyberbullying_type",
    y="text_len",
    palette="Set2",
    showfliers=False
)

plt.xticks(rotation=45)
plt.title("Text Length by Class")
plt.xlabel("Class")
plt.ylabel("Word Count")
plt.show()

from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

stop_count = sum(word in stop_words for word in all_words)
print("Stopword ratio:", stop_count / len(all_words))

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(ngram_range=(2,2), max_features=20)

X = vectorizer.fit_transform(df_raw["tweet_text"])

print(vectorizer.get_feature_names_out())

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Assuming X was already transformed by vectorizer in the previous cell
# vectorizer was fit on df_raw["tweet_text"]

# Sum the frequencies of each bigram across all documents
# Convert to a 1D numpy array using .A1 (attribute for scipy.sparse matrices)
bigram_counts = X.sum(axis=0).A1

# Get the feature names (bigrams)
bigram_names = vectorizer.get_feature_names_out()

# Create a DataFrame for bigram frequencies
bigram_freq = pd.DataFrame({
    'bigram': bigram_names,
    'count': bigram_counts
})

# Sort by count and get the top 20
bigram_freq = bigram_freq.sort_values(by='count', ascending=False).head(20)

sns.barplot(
    data=bigram_freq,
    x="count",
    y="bigram",
    palette="viridis"
)

plt.title("Top 20 Most Frequent Bigrams")
plt.xlabel("Frequency")
plt.ylabel("Bigram")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# lunghezza testo
df_raw['text_len'] = df_raw['tweet_text'].str.split().apply(len)

sns.set_theme(style="whitegrid")

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# ordine classi per frequenza
order = df_raw["cyberbullying_type"].value_counts().index

# --- Grafico 1: distribuzione classi (orizzontale) ---
sns.countplot(
    data=df_raw,
    y="cyberbullying_type",
    order=order,
    palette="Set2",
    ax=axes[0]
)

axes[0].set_title("Label Distribution", fontsize=13, weight="bold")
axes[0].set_xlabel("Count")
axes[0].set_ylabel("Class")

for container in axes[0].containers:
    axes[0].bar_label(container, padding=3, fontsize=10)

# --- Grafico 2: distribuzione lunghezza testo ---
sns.histplot(
    data=df_raw[df_raw['text_len'] <= 100],
    x="text_len",
    hue="cyberbullying_type",
    bins=40,
    kde=True,
    palette="Set2",
    alpha=0.6,
    ax=axes[1]
)

axes[1].set_title("Text Length Distribution by Class (<=100 words)", fontsize=13, weight="bold")
axes[1].set_xlabel("Word Count")
axes[1].set_ylabel("Frequency")

plt.suptitle("EDA — Cyberbullying Dataset", fontsize=15, weight="bold")
plt.tight_layout()
plt.show()

from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

vectorizer = CountVectorizer(
    stop_words="english",
    max_features=1000
)

X = vectorizer.fit_transform(df_raw["tweet_text"])
words = vectorizer.get_feature_names_out()

word_counts = pd.DataFrame(
    X.toarray(),
    columns=words
)

word_counts["label"] = df_raw["cyberbullying_type"].values

classes = word_counts["label"].unique()

fig, axes = plt.subplots(len(classes), 1, figsize=(10, 4*len(classes)))

for i, label in enumerate(classes):

    subset = word_counts[word_counts["label"] == label]

    top_words = (
        subset.drop(columns="label")
        .sum()
        .sort_values(ascending=False)
        .head(10)
    )

    sns.barplot(
        x=top_words.values,
        y=top_words.index,
        ax=axes[i],
        palette="viridis"
    )

    axes[i].set_title(f"Top Words — {label}")
    axes[i].set_xlabel("Frequency")
    axes[i].set_ylabel("Word")

plt.tight_layout()
plt.show()

top_matrix = word_counts.groupby("label").sum()

top_matrix = top_matrix.loc[:, top_matrix.sum().sort_values(ascending=False)[:20].index]

plt.figure(figsize=(12,6))

sns.heatmap(
    top_matrix,
    cmap="magma"
)

plt.title("Word Frequency Heatmap by Class")
plt.xlabel("Word")
plt.ylabel("Class")
plt.show()

plt.figure(figsize=(10,5))

sns.violinplot(
    data=df_raw[df_raw["text_len"] <= 100],
    x="cyberbullying_type",
    y="text_len",
    palette="Set2"
)

plt.xticks(rotation=45)
plt.title("Text Length Distribution by Class")
plt.xlabel("Class")
plt.ylabel("Word Count")

plt.show()

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import normalize
import umap
import plotly.express as px
import pandas as pd

vectorizer = CountVectorizer(max_features=100)
X = vectorizer.fit_transform(df_raw['clean_text'])
words = vectorizer.get_feature_names_out()
freq = X.toarray().sum(axis=0)

reducer = umap.UMAP(random_state=42)
emb_2d = reducer.fit_transform(normalize(X.T))

df_plot = pd.DataFrame({
    'x': emb_2d[:,0],
    'y': emb_2d[:,1],
    'word': words,
    'freq': freq
})


fig = px.scatter(
    df_plot, x='x', y='y', text='word',
    size='freq', color='freq',
    hover_data=['word', 'freq'],
    title='Interactive Word Embeddings Map',
    width=900, height=700
)

fig.update_traces(textposition='top center', marker=dict(opacity=0.8))
fig.show()

"""# Section 7: Oversampling and loading"""

# oversampling only on train
from imblearn.over_sampling import RandomOverSampler
import numpy as np
import pandas as pd

# Original non-oversampled data from df_train
# Make copies to ensure we're working with the initial split, not already modified global variables
X_train_initial_clean = df_train["text_clean"].values.copy()
X_train_initial_raw = df_train["text_raw"].values.copy()
y_train_initial = df_train["label_enc"].values.copy()

# Creo un dizionario con 8.000 esempi per ciascuna classe
classes = np.unique(y_train_initial)
sampling_dict = {cls: 8000 for cls in classes}

# Inizializzo oversampler
ros = RandomOverSampler(sampling_strategy=sampling_dict, random_state=42)

# Oversample the indices to apply the same sampling strategy to all related arrays
original_indices = np.arange(len(y_train_initial)).reshape(-1, 1)

# Fit and resample on these indices and the labels.
# The X_res will contain the oversampled indices.
indices_resampled, y_res = ros.fit_resample(original_indices, y_train_initial)

# Now use these resampled indices to create the new X_train, X_train_raw, and y_train
X_train = X_train_initial_clean[indices_resampled.flatten()]
X_train_raw = X_train_initial_raw[indices_resampled.flatten()]
y_train = y_res

print(f"Oversampled X_train length: {len(X_train)}")
print(f"Oversampled X_train_raw length: {len(X_train_raw)}")
print(f"Oversampled y_train length: {len(y_train)}")

# ── 4.1 Results Registry ─────────────────────────────────────────────────────
RESULTS = {}  # {"ModelName | split": {metric: value}}


# ── 4.2 Classification Evaluation ────────────────────────────────────────────
def evaluate_clf(model_name: str, y_true, y_pred,
                 y_prob=None, label_encoder=None, split: str = "test") -> dict:
    """
    Computes and prints classification metrics; stores them in RESULTS.

    Parameters
    ----------
    model_name    : display name for the model
    y_true        : ground-truth encoded labels
    y_pred        : predicted encoded labels
    y_prob        : class probabilities shape (n, 2) — binary tasks only, for ROC-AUC
    label_encoder : fitted sklearn LabelEncoder (for human-readable class names)
    split         : "val" or "test"

    Returns
    -------
    dict of computed metrics
    """
    acc       = accuracy_score(y_true, y_pred)
    f1_macro  = f1_score(y_true, y_pred, average="macro",    zero_division=0)
    f1_weight = f1_score(y_true, y_pred, average="weighted", zero_division=0)
    auc = (
        roc_auc_score(y_true, y_prob[:, 1])
        if (y_prob is not None and y_prob.shape[1] == 2) else None
    )

    print(f"\n{'='*55}")
    print(f"  {model_name} | {split.upper()}")
    print(f"{'='*55}")
    print(f"  Accuracy      : {acc:.4f}")
    print(f"  F1 (macro)    : {f1_macro:.4f}")
    print(f"  F1 (weighted) : {f1_weight:.4f}")
    if auc is not None:
        print(f"  ROC-AUC       : {auc:.4f}")

    class_names = label_encoder.classes_.tolist() if label_encoder else None
    print()
    print(classification_report(y_true, y_pred, target_names=class_names, zero_division=0))

    metrics = {"accuracy": acc, "f1_macro": f1_macro, "f1_weighted": f1_weight}
    if auc is not None:
        metrics["roc_auc"] = auc

    RESULTS[f"{model_name} | {split}"] = metrics
    return metrics


# ── 4.3 Confusion Matrix Plot ─────────────────────────────────────────────────
def plot_confusion_matrix_clf(y_true, y_pred, model_name: str, label_encoder=None):
    """
    Plots raw-count and row-normalised confusion matrices side by side.
    Saves figure to outputs/.
    """
    cm     = confusion_matrix(y_true, y_pred)
    labels = label_encoder.classes_ if label_encoder else np.unique(y_true)
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    for ax, data, title, fmt in zip(
        axes, [cm, cm_norm], ["Raw Counts", "Normalized"], ["d", ".2f"]
    ):
        sns.heatmap(data, annot=True, fmt=fmt, cmap="Blues",
                    xticklabels=labels, yticklabels=labels, ax=ax)
        ax.set_xlabel("Predicted")
        ax.set_ylabel("Actual")
        ax.set_title(title)

    plt.suptitle(f"Confusion Matrix — {model_name}", fontsize=13)
    plt.tight_layout()
    fname = CFG["output_dir"] / f"cm_{model_name.replace(' ', '_')}.png"
    plt.savefig(fname, dpi=120)
    plt.show()


# ── 4.4 Training History Plot ────────────────────────────────────────────────
def plot_history(history: dict, model_name: str):
    """
    Plots loss and F1-macro curves over epochs.

    Expected history keys:
        "train_loss"   : list[float]
        "val_loss"     : list[float]
        "val_f1_macro" : list[float]
    """
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    axes[0].plot(history["train_loss"], label="Train", marker="o")
    axes[0].plot(history["val_loss"],   label="Val",   marker="o")
    axes[0].set_title("Loss")
    axes[0].set_xlabel("Epoch")
    axes[0].legend()

    axes[1].plot(history["val_f1_macro"], marker="o", color="orange")
    axes[1].set_title("Val F1 Macro")
    axes[1].set_xlabel("Epoch")

    plt.suptitle(model_name, fontsize=13)
    plt.tight_layout()
    fname = CFG["output_dir"] / f"history_{model_name.replace(' ', '_')}.png"
    plt.savefig(fname, dpi=120)
    plt.show()


# ── 4.5 Results Summary Table ────────────────────────────────────────────────
def print_results_table():
    """Prints a formatted comparison table of all models stored in RESULTS."""
    if not RESULTS:
        print("RESULTS is empty — run evaluate_clf first.")
        return

    all_cols = sorted({k for v in RESULTS.values() for k in v.keys()})
    header = f"{'Model':<35}" + "".join(f"{c:>14}" for c in all_cols)
    sep = "=" * len(header)
    print(f"\n{sep}\n{header}\n{sep}")
    for name, metrics in RESULTS.items():
        row = f"{name:<35}" + "".join(
            f"{metrics.get(c, float('nan')):>14.4f}" for c in all_cols
        )
        print(row)
    print(sep)


print("Evaluation utilities ready.")

"""#Section 8: Baseline model"""

# ── 5.1 Majority Class Baseline ───────────────────────────────────────────────
dummy = DummyClassifier(strategy="most_frequent", random_state=CFG["seed"])
dummy.fit(X_train, y_train)
dummy_preds = dummy.predict(X_test)

evaluate_clf("Majority Baseline", y_test, dummy_preds, label_encoder=le)

"""# Section 9: TF-IDF + Logistic Regression"""

def build_tfidf(word_ngrams=(1, 2), char_ngrams=True, max_features=30000):
    from scipy.sparse import hstack

    word_vec = TfidfVectorizer(
        analyzer="word",
        ngram_range=word_ngrams,
        max_features=max_features,
        sublinear_tf=True,
        min_df=3,
        max_df=0.95
    )

    X_tr_w = word_vec.fit_transform(X_train)
    X_va_w = word_vec.transform(X_val)
    X_te_w = word_vec.transform(X_test)

    print("Word features:", X_tr_w.shape[1])

    if char_ngrams:
        char_vec = TfidfVectorizer(
            analyzer="char_wb",
            ngram_range=(3, 5),
            max_features=10000,
            sublinear_tf=True,
            min_df=3
        )

        X_tr_c = char_vec.fit_transform(X_train)
        X_va_c = char_vec.transform(X_val)
        X_te_c = char_vec.transform(X_test)

        print("Char features:", X_tr_c.shape[1])

        X_tr = hstack([X_tr_w, X_tr_c])
        X_va = hstack([X_va_w, X_va_c])
        X_te = hstack([X_te_w, X_te_c])

        print("Total features:", X_tr.shape[1])

        return X_tr, X_va, X_te, (word_vec, char_vec)

    print("Total features:", X_tr_w.shape[1])
    return X_tr_w, X_va_w, X_te_w, (word_vec,)

# Restore missing configuration parameters to CFG dictionary
# These values were overwritten by a previous cell's CFG redefinition.
# Assuming original values from global config (cell -Ht-1nLAqoRl).
CFG["tfidf_word_ngrams"] = (1, 2)
CFG["use_char_ngrams"] = True

X_tr_tfidf, X_va_tfidf, X_te_tfidf, tfidf_vecs = build_tfidf(
    word_ngrams=CFG["tfidf_word_ngrams"],
    char_ngrams=CFG["use_char_ngrams"]
)

print(f"TF-IDF feature dim: {X_tr_tfidf.shape[1]:,}")

# ── 5.3 TF-IDF + Logistic Regression ─────────────────────────────────────────

# Restore missing class_weight and cross-validation configuration parameters from the original CFG
# These values were overwritten by a previous cell's CFG redefinition.
# Assuming original values from global config (cell -Ht-1nLAqoRl).
CFG["class_weight"] = "balanced"
CFG["use_cv"] = True
CFG["cv_folds"] = 5
# Restore Path objects for directories
CFG["output_dir"] = Path("outputs/")
CFG["model_dir"] = Path("models/")

logreg = LogisticRegression(
    max_iter=1000, C=1.0,
    class_weight=CFG["class_weight"],
    solver="saga",
    random_state=CFG["seed"]
)

if CFG["use_cv"]:
    cv_scores = cross_val_score(
        logreg, X_tr_tfidf, y_train,
        cv=cv, scoring="f1_macro", n_jobs=-1
    )
    print(f"[LogReg CV] F1-macro: {cv_scores.mean():.4f} ± {cv_scores.std():.4f}")

logreg.fit(X_tr_tfidf, y_train)

evaluate_clf("TF-IDF + LogReg", y_val,
             logreg.predict(X_va_tfidf), label_encoder=le, split="val")
evaluate_clf("TF-IDF + LogReg", y_test,
             logreg.predict(X_te_tfidf),
             logreg.predict_proba(X_te_tfidf), label_encoder=le)
plot_confusion_matrix_clf(y_test, logreg.predict(X_te_tfidf), "TF-IDF + LogReg", le)

joblib.dump(logreg, CFG["model_dir"] / "logreg.pkl")

from pathlib import Path

model_path = Path("models/logreg.pkl")
print(model_path.resolve())

!ls -l models/

from pathlib import Path

model_path = Path("models/logreg.pkl")
print(model_path.resolve())

######## MODELLO SU DRIVE
import shutil
from pathlib import Path

# Colab: modello salvato localmente
local_model_path = Path("models/logreg.pkl")

# Drive: cartella che hai creato manualmente
drive_model_dir = Path("/content/drive/MyDrive/models")

# Copia su Drive
shutil.copy(local_model_path, drive_model_dir)
print(f"Modello copiato su Drive: {drive_model_dir / 'logreg.pkl'}")

# versione nuova di xgboost con gpu
!pip install --upgrade xgboost --quiet

import torch
torch.cuda.is_available()

import xgboost
print(xgboost.__version__)

"""# Section 10: TF-IDF + XGBoost"""

# ── 5.4 TF-IDF + XGBoost (GPU Ready, no CV) ─────────────────────────────
xgb = XGBClassifier(
    n_estimators=250,           # massimo numero di alberi
    max_depth=6,                # profondità massima
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method="hist",     # Changed from "gpu_hist" to "hist" for compatibility
    eval_metric="mlogloss",
    random_state=CFG["seed"],
    verbosity=1                 # mostra progresso al passo
)

# Fit finale
xgb.fit(
    X_tr_tfidf, y_train,
    eval_set=[(X_va_tfidf, y_val)],
    # early_stopping_rounds=20,  # rimosso per compatibilità con la versione di XGBoost
    verbose=True                # stampa progresso in tempo reale
)

# Predizioni
xgb_val_preds = xgb.predict(X_va_tfidf)
xgb_test_preds = xgb.predict(X_te_tfidf)

# Valutazioni e plot confusion matrix
evaluate_clf("TF-IDF + XGBoost (GPU)", y_val, xgb_val_preds, label_encoder=le, split="val")
evaluate_clf("TF-IDF + XGBoost (GPU)", y_test, xgb_test_preds, xgb.predict_proba(X_te_tfidf), label_encoder=le)
plot_confusion_matrix_clf(y_test, xgb_test_preds, "TF-IDF + XGBoost (GPU)", le)

# Salvataggio modello
joblib.dump(xgb, CFG["model_dir"] / "xgboost_gpu.pkl")

import shutil
from pathlib import Path

# Modello locale
local_model_path = Path("models/xgboost_gpu.pkl")

# Cartella Drive dove vuoi salvarlo (che hai già creato)
drive_model_dir = Path("/content/drive/MyDrive/models")

# Copia su Drive
shutil.copy(local_model_path, drive_model_dir)
print(f"Modello copiato su Drive: {drive_model_dir / 'xgboost_gpu.pkl'}")

"""# Section 11: Utilities"""

# try load
import joblib

xgb = joblib.load(drive_model_dir / "xgboost_gpu.pkl")

# ── 6.1 Vocabulary Builder ────────────────────────────────────────────────────
# Restore missing vocab_size configuration parameter from the original CFG
# This value was overwritten by a previous cell's CFG redefinition.
# Assuming original value from global config (cell -Ht-1nLAqoRl).
CFG["vocab_size"] = 30_000
CFG["pad_token"] = "<PAD>"
CFG["unk_token"] = "<UNK>"

def build_vocab(texts, max_vocab: int = 30_000,
                pad_token: str = "<PAD>", unk_token: str = "<UNK>") -> dict:
    """
    Builds word → index mapping from tokenised training texts.
    Index 0 = PAD (all-zeros row), Index 1 = UNK.
    """
    counter = Counter()
    for text in texts:
        counter.update(str(text).split())

    vocab = {pad_token: 0, unk_token: 1}
    for word, _ in counter.most_common(max_vocab - 2):
        vocab[word] = len(vocab)
    return vocab


vocab = build_vocab(
    X_train,
    max_vocab=CFG["vocab_size"],
    pad_token=CFG["pad_token"],
    unk_token=CFG["unk_token"]
)
print(f"Vocabulary size: {len(vocab):,}")

# ── 6.2 Embedding Matrix ──────────────────────────────────────────────────────
# Restore missing embedding configuration parameters from the original CFG
# These values were overwritten by a previous cell's CFG redefinition.
# Assuming original values from global config (cell -Ht-1nLAqoRl).
CFG["embedding_model"] = "glove-wiki-gigaword-100" # or "fasttext-wiki-news-subwords-300"
CFG["embedding_dim"] = 100

def load_embedding_matrix(vocab: dict, model_name: str, embed_dim: int) -> np.ndarray:
    """
    Downloads a pre-trained gensim embedding model and builds a numpy matrix
    aligned with `vocab`. Unknown words get random uniform initialisations.

    Parameters
    ----------
    vocab      : {word: index} mapping
    model_name : gensim key (e.g. "glove-wiki-gigaword-100")
    embed_dim  : embedding dimensionality

    Returns
    -------
    np.ndarray of shape (vocab_size, embed_dim)
    """
    print(f"Loading {model_name} ...")
    wv = api.load(model_name)

    matrix = np.zeros((len(vocab), embed_dim), dtype=np.float32)
    hits = misses = 0
    for word, idx in vocab.items():
        if word in wv:
            matrix[idx] = wv[word]
            hits += 1
        else:
            matrix[idx] = np.random.uniform(-0.25, 0.25, embed_dim)
            misses += 1

    matrix[0] = 0.0  # PAD stays all-zeros
    print(f"Coverage: {hits/(hits+misses)*100:.1f}%  (hits={hits}, misses={misses})")
    return matrix


embedding_matrix = load_embedding_matrix(
    vocab, CFG["embedding_model"], CFG["embedding_dim"]
)
print(f"Embedding matrix shape: {embedding_matrix.shape}")

# ── 6.3 Text → Padded Token-ID Sequences ─────────────────────────────────────


CFG["max_seq_len"] = 128

def texts_to_sequences(texts, vocab: dict, max_len: int,
                       unk_token: str = "<UNK>") -> np.ndarray:
    """
    Converts a list of strings to a (N, max_len) int32 numpy array.
    Truncates long sequences; pads short ones with 0 (PAD index).
    """
    unk_idx = vocab.get(unk_token, 1)
    seqs = np.zeros((len(texts), max_len), dtype=np.int32)
    for i, text in enumerate(texts):
        tokens = str(text).split()[:max_len]
        for j, tok in enumerate(tokens):
            seqs[i, j] = vocab.get(tok, unk_idx)
    return seqs


seq_train = texts_to_sequences(X_train, vocab, CFG["max_seq_len"])
seq_val   = texts_to_sequences(X_val,   vocab, CFG["max_seq_len"])
seq_test  = texts_to_sequences(X_test,  vocab, CFG["max_seq_len"])

print(f"seq_train: {seq_train.shape} | seq_val: {seq_val.shape} | seq_test: {seq_test.shape}")

# ── 6.4 PyTorch Dataset & DataLoaders ────────────────────────────────────────
# Restore missing dl_batch_size configuration parameter from the original CFG
# This value was overwritten by a previous cell's CFG redefinition.
# Assuming original value from global config (cell -Ht-1nLAqoRl).
CFG["dl_batch_size"] = 64

class TextSequenceDataset(Dataset):
    """
    Wraps padded token-ID sequences and integer class labels for classification.

    Parameters
    ----------
    sequences : np.ndarray shape (N, max_len)
    labels    : np.ndarray shape (N,) — integer class indices
    """
    def __init__(self, sequences: np.ndarray, labels: np.ndarray):
        self.sequences = torch.tensor(sequences, dtype=torch.long)
        self.labels    = torch.tensor(labels,    dtype=torch.long)

    def __len__(self):
        return len(self.sequences)

    def __getitem__(self, idx):
        return self.sequences[idx], self.labels[idx]


def make_loaders(seq_tr, y_tr, seq_va, y_va, seq_te, y_te,
                 batch_size: int = 64):
    """Creates train / val / test DataLoaders."""
    loader_train = DataLoader(TextSequenceDataset(seq_tr, y_tr),
                              batch_size=batch_size, shuffle=True,  num_workers=0, pin_memory=True)
    loader_val   = DataLoader(TextSequenceDataset(seq_va, y_va),
                              batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=True)
    loader_test  = DataLoader(TextSequenceDataset(seq_te, y_te),
                              batch_size=batch_size, shuffle=False, num_workers=0, pin_memory=True)
    return loader_train, loader_val, loader_test


loader_train, loader_val, loader_test = make_loaders(
    seq_train, y_train, seq_val, y_val, seq_test, y_test,
    batch_size=CFG["dl_batch_size"]
)
print("DataLoaders ready.")

# ── 7.0 Logging Setup ─────────────────────────────────────────────────────────
def get_logger(model_name: str) -> logging.Logger:
    log_path = CFG["log_dir"] / f"{CFG['task']}_{model_name.replace(' ', '_')}.log"

    logger = logging.getLogger(model_name)
    logger.setLevel(logging.DEBUG)
    logger.handlers.clear()
    logger.propagate = False

    fh = logging.FileHandler(log_path, mode="w", encoding="utf-8")
    fh.setLevel(logging.DEBUG)
    fh.setFormatter(logging.Formatter(
        "%(asctime)s | %(levelname)-8s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S"
    ))

    ch = logging.StreamHandler(sys.stdout)
    ch.setLevel(logging.INFO)
    ch.setFormatter(logging.Formatter("%(message)s"))

    logger.addHandler(fh)
    logger.addHandler(ch)
    return logger


# ── 7.1 Single Epoch Helpers ──────────────────────────────────────────────────
def _train_epoch(model, loader, optimizer, criterion, device):
    """One training pass. Returns average cross-entropy loss."""
    model.train()
    total_loss = 0.0
    for seqs, labels in loader:
        seqs, labels = seqs.to(device), labels.to(device)
        optimizer.zero_grad()
        loss = criterion(model(seqs), labels)
        loss.backward()
        nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        optimizer.step()
        total_loss += loss.item() * seqs.size(0)
    return total_loss / len(loader.dataset)


@torch.no_grad()
def _eval_epoch(model, loader, criterion, device):
    model.eval()
    total_loss, all_preds, all_labels = 0.0, [], []
    for seqs, labels in loader:
        seqs, labels = seqs.to(device), labels.to(device)
        logits = model(seqs)
        total_loss += criterion(logits, labels).item() * seqs.size(0)
        all_preds.extend(logits.argmax(dim=1).cpu().numpy())
        all_labels.extend(labels.cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    f1_macro = f1_score(all_labels, all_preds, average="macro", zero_division=0)
    return avg_loss, f1_macro, np.array(all_preds)


# ── 7.2 Main Training Loop ────────────────────────────────────────────────────
def train_model(model, loader_tr, loader_va, model_name: str,
                epochs: int = 20, lr: float = 1e-3,
                patience: int = 3, device: str = "cpu",
                resume: bool = True) -> dict:
    model     = model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = ReduceLROnPlateau(optimizer, mode="max", factor=0.5, patience=1)

    logger = get_logger(model_name)
    tb_dir = CFG["log_dir"] / "tensorboard" / f"{CFG['task']}_{model_name.replace(' ', '_')}"
    writer = SummaryWriter(log_dir=tb_dir)

    history    = {"train_loss": [], "val_loss": [], "val_f1_macro": []}
    best_f1    = -np.inf
    no_improve = 0
    start_epoch = 1

    # --- checkpoint paths
    safe_name = model_name.replace(" ", "_")
    ckpt_dir = CFG["model_dir"] / safe_name
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    best_ckpt_path = ckpt_dir / "best.pt"
    last_ckpt_path = ckpt_dir / "last.pt"

    # --- optional resume
    if resume and last_ckpt_path.exists():
        ckpt = torch.load(last_ckpt_path, map_location=device)
        model.load_state_dict(ckpt["model_state"])
        optimizer.load_state_dict(ckpt["optimizer_state"])
        scheduler.load_state_dict(ckpt["scheduler_state"])
        history = ckpt.get("history", history)
        best_f1 = ckpt.get("best_f1", best_f1)
        no_improve = ckpt.get("no_improve", 0)
        start_epoch = ckpt.get("epoch", 0) + 1
        logger.info(f"Resumed from {last_ckpt_path} (epoch={start_epoch-1}, best_f1={best_f1:.4f})")

    for epoch in range(start_epoch, epochs + 1):
        t0 = time.time()
        tr_loss           = _train_epoch(model, loader_tr, optimizer, criterion, device)
        va_loss, va_f1, _ = _eval_epoch(model, loader_va, criterion, device)
        elapsed           = time.time() - t0

        history["train_loss"].append(tr_loss)
        history["val_loss"].append(va_loss)
        history["val_f1_macro"].append(va_f1)
        scheduler.step(va_f1)

        writer.add_scalars("loss", {"train": tr_loss, "val": va_loss}, epoch)
        writer.add_scalar("val/f1_macro", va_f1, epoch)
        writer.add_scalar("train/lr", optimizer.param_groups[0]["lr"], epoch)

        # always save LAST checkpoint (for recovery)
        last_payload = {
            "epoch": epoch,
            "model_state": model.state_dict(),
            "optimizer_state": optimizer.state_dict(),
            "scheduler_state": scheduler.state_dict(),
            "best_f1": best_f1,
            "no_improve": no_improve,
            "history": history,
            "model_name": model_name,
            "task": CFG["task"],
        }
        torch.save(last_payload, last_ckpt_path)

        # save BEST checkpoint
        if va_f1 > best_f1:
            best_f1 = va_f1
            no_improve = 0
            best_payload = {
                "epoch": epoch,
                "model_state": model.state_dict(),
                "optimizer_state": optimizer.state_dict(),
                "scheduler_state": scheduler.state_dict(),
                "best_f1": best_f1,
                "history": history,
                "model_name": model_name,
                "task": CFG["task"],
            }
            torch.save(best_payload, best_ckpt_path)
            tag = " ✓  <-- new best"
        else:
            no_improve += 1
            tag = ""

        logger.info(
            f"Epoch {epoch:>3}/{epochs} | tr_loss={tr_loss:.4f} | "
            f"va_loss={va_loss:.4f} | val_f1={va_f1:.4f} | {elapsed:.1f}s{tag}"
        )

        if no_improve >= patience:
            logger.info(f"Early stopping triggered at epoch {epoch}.")
            break

    # restore BEST weights from disk
    if best_ckpt_path.exists():
        best_ckpt = torch.load(best_ckpt_path, map_location=device)
        model.load_state_dict(best_ckpt["model_state"])
        logger.info(f"Restored best checkpoint | val_f1={best_ckpt['best_f1']:.4f} | path={best_ckpt_path}")

    writer.close()
    logger.info("Training complete.")
    return history


# ── 7.3 Batch Prediction Helper ───────────────────────────────────────────────
@torch.no_grad()
def predict(model, loader, device: str = "cpu") -> np.ndarray:
    model.eval()
    all_preds = []
    for seqs, _ in loader:
        all_preds.extend(model(seqs.to(device)).argmax(dim=1).cpu().numpy())
    return np.array(all_preds)


print("Training loop utilities ready.")

"""# Section 12: Text CNN

"""

# ── 8.1 EmbeddingMLP ─────────────────────────────────────────────────────────
class EmbeddingMLP(nn.Module):
    """
    Mean-pools pre-trained token embeddings, then applies a two-layer MLP.
    Serves as the lightweight "GloVe + MLP" step in the pipeline.

    Parameters
    ----------
    embedding_matrix : np.ndarray, shape (vocab_size, embed_dim)
    num_classes      : number of output classes
    hidden_dim       : hidden layer width
    dropout          : dropout probability
    freeze_emb       : if True, embedding weights are not updated during training
    """
    def __init__(self, embedding_matrix: np.ndarray, num_classes: int,
                 hidden_dim: int = 256, dropout: float = 0.3,
                 freeze_emb: bool = False):
        super().__init__()
        _, embed_dim = embedding_matrix.shape
        self.embedding = nn.Embedding.from_pretrained(
            torch.FloatTensor(embedding_matrix), freeze=freeze_emb, padding_idx=0
        )
        self.fc = nn.Sequential(
            nn.Linear(embed_dim, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, num_classes)
        )

    def forward(self, x):
        mask = (x != 0).float().unsqueeze(-1)       # (B, L, 1) — zero out PAD
        emb  = self.embedding(x) * mask             # (B, L, D)
        doc  = emb.sum(1) / mask.sum(1).clamp(min=1)  # masked mean → (B, D)
        return self.fc(doc)


# ── 8.2 TextCNN ───────────────────────────────────────────────────────────────
class TextCNN(nn.Module):
    """
    Parallel Conv1d filters over token embeddings with global max-pooling.

    Parameters
    ----------
    embedding_matrix : np.ndarray, shape (vocab_size, embed_dim)
    num_classes      : number of output classes
    num_filters      : number of filters per kernel size
    kernel_sizes     : list of filter heights (e.g. [2, 3, 4])
    dropout          : dropout probability
    freeze_emb       : if True, embedding weights are frozen
    """
    def __init__(self, embedding_matrix: np.ndarray, num_classes: int,
                 num_filters: int = 128, kernel_sizes: list = None,
                 dropout: float = 0.3, freeze_emb: bool = False):
        super().__init__()
        if kernel_sizes is None:
            kernel_sizes = [2, 3, 4]

        _, embed_dim = embedding_matrix.shape
        self.embedding = nn.Embedding.from_pretrained(
            torch.FloatTensor(embedding_matrix), freeze=freeze_emb, padding_idx=0
        )
        self.convs = nn.ModuleList([
            nn.Conv1d(embed_dim, num_filters, kernel_size=k, padding=k // 2)
            for k in kernel_sizes
        ])
        self.dropout = nn.Dropout(dropout)
        self.fc      = nn.Linear(num_filters * len(kernel_sizes), num_classes)

    def forward(self, x):
        emb = self.embedding(x).permute(0, 2, 1)    # (B, D, L)
        pooled = [
            F.relu(conv(emb)).max(dim=2).values      # (B, F)
            for conv in self.convs
        ]
        return self.fc(self.dropout(torch.cat(pooled, dim=1)))


print("EmbeddingMLP and TextCNN architectures defined.")

# ── 8.3 Train EmbeddingMLP ────────────────────────────────────────────────────
# Restore missing num_labels configuration parameter from the original CFG
# This value was overwritten by a previous cell's CFG redefinition.
# The actual number of classes is derived from the LabelEncoder.
CFG["num_labels"] = len(le.classes_)
# Restore missing dropout configuration parameter from the original CFG
# This value was overwritten by a previous cell's CFG redefinition.
# Assuming original value from global config (cell -Ht-1nLAqoRl).
CFG["dropout"] = 0.3
# Restore missing deep learning configuration parameters from the original CFG
# These values were overwritten by a previous cell's CFG redefinition.
# Assuming original values from global config (cell -Ht-1nLAqoRl).
CFG["dl_epochs"] = 20
CFG["dl_lr"] = 1e-3
CFG["dl_patience"] = 3
CFG["device"] = (
    "mps"  if torch.backends.mps.is_available() and torch.backends.mps.is_built()
    else "cuda" if torch.cuda.is_available()
    else "cpu"
)
# Restore Path objects for directories
CFG["output_dir"] = Path("outputs/")
CFG["model_dir"] = Path("models/")
CFG["log_dir"] = Path("logs/")

set_seed(CFG["seed"])
mlp_model = EmbeddingMLP(
    embedding_matrix=embedding_matrix,
    num_classes=CFG["num_labels"],
    hidden_dim=256,
    dropout=CFG["dropout"]
)
print(f"MLP params: {sum(p.numel() for p in mlp_model.parameters()):,}")

mlp_history = train_model(
    mlp_model, loader_train, loader_val,
    model_name="GloVe MLP",
    epochs=CFG["dl_epochs"], lr=CFG["dl_lr"],
    patience=CFG["dl_patience"], device=CFG["device"]
)
plot_history(mlp_history, "GloVe MLP")

mlp_preds = predict(mlp_model, loader_test, CFG["device"])
evaluate_clf("GloVe MLP", y_test, mlp_preds, label_encoder=le)
plot_confusion_matrix_clf(y_test, mlp_preds, "GloVe MLP", le)

import torch
from pathlib import Path
import shutil

# Cartella locale dove il modello è salvato temporaneamente
local_model_path = Path("models/mlp.pth")

# Salvataggio del modello PyTorch localmente
torch.save(mlp_model.state_dict(), local_model_path)
print(f"MLP salvato localmente: {local_model_path}")

# Cartella Drive dove vuoi copiarlo (già creata)
drive_model_dir = Path("/content/drive/MyDrive/models")

# Copia su Drive
shutil.copy(local_model_path, drive_model_dir)
print(f"MLP copiato su Drive: {drive_model_dir / 'mlp.pth'}")

# rebuild architecture
mlp_model = EmbeddingMLP(
    embedding_matrix=embedding_matrix,
    num_classes=CFG["num_labels"],
    hidden_dim=256,
    dropout=CFG["dropout"]
)

# load weights
mlp_model.load_state_dict(torch.load(drive_model_dir / "mlp.pth", map_location=CFG["device"]))
mlp_model.to(CFG["device"])
mlp_model.eval()

"""# Section 13: BiLSTM + Attention"""

# ── 9.1 Additive Attention ────────────────────────────────────────────────────
class AdditiveAttention(nn.Module):
    """
    Computes a weighted average over LSTM hidden states.
    Weights are learned via a single linear layer + softmax.
    Padding positions are masked out before softmax.
    """
    def __init__(self, hidden_dim: int):
        super().__init__()
        self.attn = nn.Linear(hidden_dim, 1, bias=False)

    def forward(self, h, mask=None):
        scores = self.attn(h).squeeze(-1)                       # (B, L)
        if mask is not None:
            scores = scores.masked_fill(~mask, -1e9)
        weights = torch.softmax(scores, dim=1)                  # (B, L)
        context = (weights.unsqueeze(-1) * h).sum(dim=1)        # (B, H)
        return context, weights


# ── 9.2 BiLSTM + Attention ────────────────────────────────────────────────────
class BiLSTMAttention(nn.Module):
    """
    Bidirectional LSTM with additive attention for text classification.

    Parameters
    ----------
    embedding_matrix : np.ndarray, shape (vocab_size, embed_dim)
    num_classes      : number of output classes
    hidden_dim       : LSTM hidden state size per direction
    num_layers       : number of stacked LSTM layers
    dropout          : dropout probability
    freeze_emb       : freeze pre-trained embeddings during training
    """
    def __init__(self, embedding_matrix: np.ndarray, num_classes: int,
                 hidden_dim: int = 128, num_layers: int = 2,
                 dropout: float = 0.3, freeze_emb: bool = False):
        super().__init__()
        _, embed_dim = embedding_matrix.shape
        self.embedding = nn.Embedding.from_pretrained(
            torch.FloatTensor(embedding_matrix), freeze=freeze_emb, padding_idx=0
        )
        self.lstm = nn.LSTM(
            input_size=embed_dim, hidden_size=hidden_dim,
            num_layers=num_layers, batch_first=True,
            bidirectional=True,
            dropout=dropout if num_layers > 1 else 0.0
        )
        self.attention = AdditiveAttention(hidden_dim * 2)   # *2 for bidirectional
        self.dropout   = nn.Dropout(dropout)
        self.fc        = nn.Linear(hidden_dim * 2, num_classes)

    def forward(self, x):
        mask = (x != 0)                              # (B, L) True = real token
        emb  = self.dropout(self.embedding(x))       # (B, L, D)
        h, _ = self.lstm(emb)                        # (B, L, 2*H)
        ctx, _ = self.attention(h, mask)             # (B, 2*H)
        return self.fc(self.dropout(ctx))


print("BiLSTMAttention architecture defined.")

# ── 9.3 Train BiLSTM + Attention ──────────────────────────────────────────────

CFG["lstm_hidden_dim"] = 128
CFG["lstm_num_layers"] = 2
CFG["dropout"] = 0.3
CFG["dl_epochs"] = 20
CFG["dl_lr"] = 1e-3
CFG["dl_patience"] = 3
CFG["device"] = (
    "mps"  if torch.backends.mps.is_available() and torch.backends.mps.is_built()
    else "cuda" if torch.cuda.is_available()
    else "cpu"
)
# Restore Path objects for directories
CFG["output_dir"] = Path("outputs/")
CFG["model_dir"] = Path("models/")
CFG["log_dir"] = Path("logs/")

set_seed(CFG["seed"])

atentos_model = BiLSTMAttention(
    embedding_matrix=embedding_matrix,
    num_classes=CFG["num_labels"],
    hidden_dim=CFG["lstm_hidden_dim"],
    num_layers=CFG["lstm_num_layers"],
    dropout=CFG["dropout"]
)
print(f"BiLSTM params: {sum(p.numel() for p in atentos_model.parameters()):,}")

att_history = train_model(
    atentos_model, loader_train, loader_val,
    model_name="GloVe BiLSTM + Att",
    epochs=CFG["dl_epochs"], lr=CFG["dl_lr"],
    patience=CFG["dl_patience"], device=CFG["device"]
)
plot_history(att_history, "GloVe BiLSTM + Att")

att_preds = predict(atentos_model, loader_test, CFG["device"])
evaluate_clf("GloVe BiLSTM + Att", y_test, att_preds, label_encoder=le)
plot_confusion_matrix_clf(y_test, att_preds, "GloVe BiLSTM + Att", le)

# Salvataggio BiLSTM + Attention su Drive
drive_model_dir = Path("/content/drive/MyDrive/models")
drive_model_dir.mkdir(exist_ok=True)
torch.save(atentos_model, drive_model_dir / "bilstm_attention_full.pth")

"""# Section 14: GloVe CNN"""

def set_seed(seed: int = 42):
    """Fix all random seeds for full reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

# ── 8.4 Train TextCNN ────────────────────────────────────────────────────────
# Restore missing configuration parameters from the original CFG
# These values were overwritten by a previous cell's CFG redefinition.
# Assuming original values from global config (cell -Ht-1nLAqoRl).
CFG["cnn_num_filters"] = 128
CFG["cnn_kernel_sizes"] = [2, 3, 4]
CFG["dropout"] = 0.3
CFG["dl_epochs"] = 20
CFG["dl_lr"] = 1e-3
CFG["dl_patience"] = 3
CFG["device"] = (
    "mps"  if torch.backends.mps.is_available() and torch.backends.mps.is_built()
    else "cuda" if torch.cuda.is_available()
    else "cpu"
)
# Restore Path objects for directories
CFG["output_dir"] = Path("outputs/")
CFG["model_dir"] = Path("models/")
CFG["log_dir"] = Path("logs/")

set_seed(CFG["seed"])
cnn_model = TextCNN(
    embedding_matrix=embedding_matrix,
    num_classes=CFG["num_labels"],
    num_filters=CFG["cnn_num_filters"],
    kernel_sizes=CFG["cnn_kernel_sizes"],
    dropout=CFG["dropout"]
)
print(f"TextCNN params: {sum(p.numel() for p in cnn_model.parameters()):,}")

cnn_history = train_model(
    cnn_model, loader_train, loader_val,
    model_name="GloVe CNN",
    epochs=CFG["dl_epochs"], lr=CFG["dl_lr"],
    patience=CFG["dl_patience"], device=CFG["device"]
)
plot_history(cnn_history, "GloVe CNN")

cnn_preds = predict(cnn_model, loader_test, CFG["device"])
evaluate_clf("GloVe CNN", y_test, cnn_preds, label_encoder=le)
plot_confusion_matrix_clf(y_test, cnn_preds, "GloVe CNN", le)

# save
drive_model_dir.mkdir(exist_ok=True)
torch.save(cnn_model, drive_model_dir / "textcnn_full.pth")

"""# Section 15:  GloVe BiLSTM"""

# ── 9.3 Train BiLSTM ──────────────────────────────────────────────────────────
set_seed(CFG["seed"])
bilstm_model = BiLSTMAttention(
    embedding_matrix=embedding_matrix,
    num_classes=CFG["num_labels"],
    hidden_dim=CFG["lstm_hidden_dim"],
    num_layers=CFG["lstm_num_layers"],
    dropout=CFG["dropout"]
)
print(f"BiLSTM params: {sum(p.numel() for p in bilstm_model.parameters()):,}")

lstm_history = train_model(
    bilstm_model, loader_train, loader_val,
    model_name="GloVe BiLSTM",
    epochs=CFG["dl_epochs"], lr=CFG["dl_lr"],
    patience=CFG["dl_patience"], device=CFG["device"]
)
plot_history(lstm_history, "GloVe BiLSTM")

bilstm_preds = predict(bilstm_model, loader_test, CFG["device"])
evaluate_clf("GloVe BiLSTM", y_test, bilstm_preds, label_encoder=le)
plot_confusion_matrix_clf(y_test, bilstm_preds, "GloVe BiLSTM", le)

# Save
drive_model_dir.mkdir(exist_ok=True)
torch.save(bilstm_model, drive_model_dir / "bilstm_full.pth")

"""# Section 16: BERT"""

# ── 10.1 HuggingFace Dataset ──────────────────────────────────────────────────
class HFTextDataset(Dataset):
    """
    PyTorch Dataset wrapping a HuggingFace tokenizer for classification.
    Compatible with HF Trainer and standard DataLoader.

    Parameters
    ----------
    texts     : list/array of raw strings
    labels    : encoded integer class indices
    tokenizer : HuggingFace tokenizer
    max_len   : maximum token length
    """
    def __init__(self, texts, labels, tokenizer, max_len: int = 256):
        self.encodings = tokenizer(
            list(texts), truncation=True, padding="max_length",
            max_length=max_len, return_tensors="pt"
        )
        self.labels = torch.tensor(labels, dtype=torch.long)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {k: v[idx] for k, v in self.encodings.items()}
        item["labels"] = self.labels[idx]
        return item


# ── 10.2 Compute Metrics for HF Trainer ──────────────────────────────────────
def compute_metrics(eval_pred) -> dict:
    """
    Passed to HuggingFace Trainer. Returns F1-macro and accuracy.
    """
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "f1_macro": f1_score(labels, preds, average="macro", zero_division=0),
        "accuracy": accuracy_score(labels, preds)
    }


print("HF Dataset and compute_metrics ready.")

# ── 10.3 Tokeniser & Datasets ─────────────────────────────────────────────────
# Restore missing configuration parameters from the original CFG
# These values were overwritten by a previous cell's CFG redefinition.
# Assuming original values from global config (cell -Ht-1nLAqoRl).
CFG["trf_model"] = "bert-base-uncased"
CFG["max_len"] = 256

trf_tokenizer = AutoTokenizer.from_pretrained(CFG["trf_model"])

trf_ds_train = HFTextDataset(X_train_raw, y_train, trf_tokenizer, CFG["max_len"])
trf_ds_val   = HFTextDataset(X_val_raw,   y_val,   trf_tokenizer, CFG["max_len"])
trf_ds_test  = HFTextDataset(X_test_raw,  y_test,  trf_tokenizer, CFG["max_len"])

print(f"Train HF dataset: {len(trf_ds_train)} | "
      f"Val: {len(trf_ds_val)} | Test: {len(trf_ds_test)}")

# ── 10.4 Model + Trainer ────────────────────────
# Restore missing configuration parameters from the original CFG
# These values were overwritten by a previous cell's CFG redefinition.
# Assuming original values from global config (cell -Ht-1nLAqoRl).
CFG["batch_size"] = 16
CFG["epochs"] = 5
CFG["lr"] = 2e-5
# Restore Path objects for directories
CFG["output_dir"] = Path("outputs/")
CFG["model_dir"] = Path("models/")
CFG["log_dir"] = Path("logs/")

out_dir = CFG["model_dir"] / "transformer"
out_dir.mkdir(parents=True, exist_ok=True)

trf_model = AutoModelForSequenceClassification.from_pretrained(
    CFG["trf_model"],
    num_labels=CFG["num_labels"],
    problem_type="single_label_classification",
    from_tf=False,
)

training_args = TrainingArguments(
    output_dir=str(out_dir),
    num_train_epochs=CFG["epochs"],
    per_device_train_batch_size=CFG["batch_size"],
    per_device_eval_batch_size=CFG["batch_size"],
    learning_rate=CFG["lr"],
    warmup_steps=int(0.06 * len(X_train_raw) / CFG["batch_size"] * CFG["epochs"]), # Use warmup_steps instead of warmup_ratio
    weight_decay=0.01,

    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro",
    greater_is_better=True,

    logging_dir=str(CFG["log_dir"] / "tensorboard"), # Use TENSORBOARD_LOGGING_DIR compatible path
    logging_strategy="epoch",
    report_to="tensorboard",

    fp16=torch.cuda.is_available(),
    seed=CFG["seed"],
)

# Recreate datasets with updated X_train_raw and y_train after oversampling
trf_ds_train = HFTextDataset(X_train_raw, y_train, trf_tokenizer, CFG["max_len"])
trf_ds_val   = HFTextDataset(X_val_raw,   y_val,   trf_tokenizer, CFG["max_len"])
trf_ds_test  = HFTextDataset(X_test_raw,  y_test,  trf_tokenizer, CFG["max_len"])

print(f"Re-created Train HF dataset: {len(trf_ds_train)} | "
      f"Val: {len(trf_ds_val)} | Test: {len(trf_ds_test)}")

trainer = Trainer(
    model=trf_model,
    args=training_args,
    train_dataset=trf_ds_train,
    eval_dataset=trf_ds_val,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)],
)

last_ckpt = get_last_checkpoint(str(out_dir))
print("Last checkpoint:", last_ckpt)

trainer.train(resume_from_checkpoint=last_ckpt if last_ckpt is not None else None)

# Directory su Drive
drive_model_dir = Path("/content/drive/MyDrive/models/transformer_best")
drive_model_dir.mkdir(parents=True, exist_ok=True)

# Salva modello e tokenizer
trainer.save_model(str(drive_model_dir))
trf_tokenizer.save_pretrained(str(drive_model_dir))

print(f"Transformer salvato su: {drive_model_dir}")

hist = trainer.state.log_history

ts = datetime.now().strftime("%Y%m%d_%H%M%S")
json_path = CFG["log_dir"] / f"trainer_log_history_{ts}.json"
with open(json_path, "w", encoding="utf-8") as f:
    json.dump(hist, f, ensure_ascii=False, indent=2)

df_hist = pd.DataFrame(hist)
csv_path = CFG["log_dir"] / f"trainer_log_history_{ts}.csv"
df_hist.to_csv(csv_path, index=False)

print("Saved:", json_path, csv_path)
display(df_hist.tail(20))

# ── 10.5 Evaluate Transformer ─────────────────────────────────────────────────
trf_val_output  = trainer.predict(trf_ds_val)
trf_test_output = trainer.predict(trf_ds_test)

trf_val_preds  = np.argmax(trf_val_output.predictions,  axis=1)
trf_test_preds = np.argmax(trf_test_output.predictions, axis=1)

evaluate_clf("BERT Fine-tune", y_val,  trf_val_preds,  label_encoder=le, split="val")
evaluate_clf("BERT Fine-tune", y_test, trf_test_preds, label_encoder=le)
plot_confusion_matrix_clf(y_test, trf_test_preds, "BERT Fine-tune", le)

# Save fine-tuned model & tokenizer
trainer.save_model(str(CFG["model_dir"] / "transformer_best"))
trf_tokenizer.save_pretrained(str(CFG["model_dir"] / "transformer_best"))
print("Transformer model saved.")

"""# Section 17: Results"""

print_results_table()

# ── 11.2 Results as DataFrame ─────────────────────────────────────────────────
df_results = (
    pd.DataFrame(RESULTS)
    .T
    .rename_axis("Model | Split")
    .sort_values("f1_macro", ascending=False)
)
display(df_results.round(4))

df_results.to_csv(CFG["output_dir"] / f"results_{CFG['task']}.csv")
print("Results saved.")

# ── 11.3 Bar Chart Comparison ─────────────────────────────────────────────────
def plot_model_comparison(results: dict, metric: str = "f1_macro",
                          split: str = "test"):
    """
    Horizontal bar chart comparing all models on `metric` for the given `split`.

    Parameters
    ----------
    results : RESULTS dict
    metric  : column to plot (e.g. "f1_macro", "accuracy")
    split   : "test" or "val" — filters RESULTS entries
    """
    filtered = {
        k.replace(f" | {split}", ""): v[metric]
        for k, v in results.items()
        if split in k and metric in v
    }
    if not filtered:
        print(f"No results for split='{split}', metric='{metric}'.")
        return

    names  = list(filtered.keys())
    values = list(filtered.values())
    order  = np.argsort(values)

    fig, ax = plt.subplots(figsize=(9, max(4, len(names) * 0.55)))
    bars = ax.barh(
        [names[i] for i in order],
        [values[i] for i in order],
        color=sns.color_palette("viridis", len(names))
    )
    for bar, val in zip(bars, [values[i] for i in order]):
        ax.text(bar.get_width() + 0.002, bar.get_y() + bar.get_height() / 2,
                f"{val:.4f}", va="center", fontsize=9)

    ax.set_xlabel(metric.replace("_", " ").title())
    ax.set_title(f"Model Comparison — {metric} ({split.upper()} set)")
    ax.set_xlim(0, min(1.05, max(values) * 1.12))
    plt.tight_layout()
    plt.savefig(CFG["output_dir"] / f"comparison_{metric}_{split}.png", dpi=120)
    plt.show()


plot_model_comparison(RESULTS, metric="f1_macro", split="test")
plot_model_comparison(RESULTS, metric="accuracy", split="test")

# ── 11.4 Error Analysis — Top Misclassified Samples ──────────────────────────
def error_analysis(df_split: pd.DataFrame, y_true, y_pred,
                   label_encoder=None, n: int = 10) -> pd.DataFrame:
    """
    Returns a DataFrame of the top-n misclassified samples.

    Parameters
    ----------
    df_split      : DataFrame for the relevant split (e.g. df_test)
    y_true, y_pred: encoded labels
    label_encoder : to decode label names
    n             : number of examples to display
    """
    err_mask = y_true != y_pred
    df_err   = df_split[err_mask].copy()
    df_err["y_true"] = y_true[err_mask]
    df_err["y_pred"] = y_pred[err_mask]

    if label_encoder is not None:
        df_err["true_label"] = label_encoder.inverse_transform(df_err["y_true"])
        df_err["pred_label"] = label_encoder.inverse_transform(df_err["y_pred"])
        cols = [CFG["text_col"], "true_label", "pred_label"]
    else:
        cols = [CFG["text_col"], "y_true", "y_pred"]

    return df_err[cols].head(n)


print("=== Error Analysis — BERT Fine-tune ===")
display(error_analysis(df_test, y_test, trf_test_preds, le, n=10))

# ── 12.1 Save All Artefacts ───────────────────────────────────────────────────
def save_artefacts():
    """Saves CFG, RESULTS, label encoder and vocab to disk."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M")

    # CFG (Path objects → str)
    cfg_serializable = {k: str(v) if isinstance(v, Path) else v
                        for k, v in CFG.items()}
    with open(CFG["output_dir"] / f"cfg_{timestamp}.json", "w") as f:
        json.dump(cfg_serializable, f, indent=2, default=str)

    # RESULTS
    with open(CFG["output_dir"] / f"results_{timestamp}.json", "w") as f:
        json.dump(RESULTS, f, indent=2)

    # Label encoder & vocab
    joblib.dump(le,    CFG["model_dir"] / "label_encoder.pkl")
    joblib.dump(vocab, CFG["model_dir"] / "vocab.pkl")

    print(f"Artefacts saved  →  {CFG['output_dir']}  |  {CFG['model_dir']}")

save_artefacts()

# TESTING BEST MODEL

MODEL_PATH = str(CFG["model_dir"] / "transformer_best")

# Load once
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_PATH)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

@torch.no_grad()
def predict_one(text: str):
    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=256
    ).to(device)

    outputs = model(**inputs)
    logits = outputs.logits

    probs = torch.softmax(logits, dim=-1)
    conf, pred_id = torch.max(probs, dim=-1)

    pred_id = int(pred_id.item())
    confidence = float(conf.item())

    # если есть label encoder
    if "le" in globals():
        pred_label = le.inverse_transform([pred_id])[0]
    else:
        pred_label = str(pred_id)

    return pred_label, confidence

label, conf = predict_one("You are a good person")
print(f"Prediction: {label}")
print(f"Confidence: {conf:.4f}")

label, conf = predict_one("You are a motherfucker!")
print(f"Prediction: {label}")
print(f"Confidence: {conf:.4f}")

label, conf = predict_one("I hope people like you won't come to my country!")
print(f"Prediction: {label}")
print(f"Confidence: {conf:.4f}")

import torch
from torch.utils.data import DataLoader
import numpy as np

device = trainer.args.device
model = trainer.model
model.eval()

test_loader = DataLoader(trf_ds_test, batch_size=32, shuffle=False)

bert_embeddings_list = []

with torch.no_grad():
    for batch in test_loader:
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)

        outputs = model.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        cls_embeddings = outputs.last_hidden_state[:, 0, :]  # CLS token
        bert_embeddings_list.append(cls_embeddings.cpu().numpy())

bert_embeddings = np.vstack(bert_embeddings_list)

print("Fine-tuned BERT embeddings shape:", bert_embeddings.shape)

from sentence_transformers import SentenceTransformer

sbert_model = SentenceTransformer("all-MiniLM-L6-v2")

sbert_embeddings = sbert_model.encode(
    list(X_test_raw),
    show_progress_bar=True
)

print("SBERT embeddings shape:", sbert_embeddings.shape)

import umap

umap_model = umap.UMAP(
    n_neighbors=15,
    min_dist=0.1,
    n_components=2,
    metric="cosine",
    random_state=42
)

sbert_2d = umap_model.fit_transform(sbert_embeddings)
bert_2d  = umap_model.fit_transform(bert_embeddings)

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df_plot = pd.DataFrame({
    "sbert_x": sbert_2d[:, 0],
    "sbert_y": sbert_2d[:, 1],
    "bert_x":  bert_2d[:, 0],
    "bert_y":  bert_2d[:, 1],
    "label": le.inverse_transform(y_test)
})

fig, axes = plt.subplots(1, 2, figsize=(18, 7))

sns.scatterplot(
    x="sbert_x", y="sbert_y",
    hue="label",
    data=df_plot,
    alpha=0.7,
    ax=axes[0]
)
axes[0].set_title("SBERT (Pre-trained)")

sns.scatterplot(
    x="bert_x", y="bert_y",
    hue="label",
    data=df_plot,
    alpha=0.7,
    ax=axes[1]
)
axes[1].set_title("BERT Fine-tuned")

plt.tight_layout()
plt.show()

from sentence_transformers import SentenceTransformer

# Modello SBERT pre-trained
sbert_model = SentenceTransformer("all-MiniLM-L6-v2")
emb_sbert = sbert_model.encode(X_test_raw, show_progress_bar=True)

import torch
from transformers import AutoModel


bert_model = AutoModel.from_pretrained(str(CFG["model_dir"] / "transformer_best"))
bert_model.eval()
bert_model.to("cuda")


def get_bert_embeddings(texts, tokenizer, model, max_len=256):
    embeddings = []
    batch_size = 16
    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i:i+batch_size]

        enc = tokenizer(batch_texts.tolist(), padding=True, truncation=True, max_length=max_len, return_tensors="pt").to("cuda")
        with torch.no_grad():
            out = model(**enc)

        cls_emb = out.last_hidden_state[:, 0, :].cpu().numpy()
        embeddings.append(cls_emb)
    return np.vstack(embeddings)

emb_bert_ft = get_bert_embeddings(X_test_raw, trf_tokenizer, bert_model, CFG["max_len"])

from sklearn.metrics import silhouette_score, davies_bouldin_score

# Usa le etichette reali (y_test) come cluster ground-truth
sil_sbert = silhouette_score(emb_sbert, y_test)
db_sbert  = davies_bouldin_score(emb_sbert, y_test)

sil_bert_ft = silhouette_score(emb_bert_ft, y_test)
db_bert_ft  = davies_bouldin_score(emb_bert_ft, y_test)

print(f"SBERT pre-trained: Silhouette={sil_sbert:.3f}, Davies-Bouldin={db_sbert:.3f}")
print(f"BERT fine-tuned : Silhouette={sil_bert_ft:.3f}, Davies-Bouldin={db_bert_ft:.3f}")

import numpy as np


topic_ids = set(topics) - {-1}
topic_embeddings = {}

for t in topic_ids:
    docs_t = [doc for doc, topic in zip(documents, topics) if topic == t]

    emb_t = embedding_model.encode(docs_t, show_progress_bar=False)
    topic_embeddings[t] = np.mean(emb_t, axis=0)

from sklearn.metrics.pairwise import cosine_similarity

topic_keys = list(topic_embeddings.keys())
emb_matrix = np.array([topic_embeddings[t] for t in topic_keys])
sim_matrix = cosine_similarity(emb_matrix)

# soglia per creare un edge tra topic
threshold = 0.5
edges = []
for i in range(len(topic_keys)):
    for j in range(i+1, len(topic_keys)):
        if sim_matrix[i, j] >= threshold:
            edges.append((topic_keys[i], topic_keys[j], sim_matrix[i, j]))

# Install pyvis library
!pip install pyvis --quiet

from pyvis.network import Network
from IPython.display import display, HTML
import random
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


topic_info = topic_model.get_topic_info()
topics = topic_info[topic_info.Topic != -1]['Topic'].tolist()
sizes = topic_info[topic_info.Topic != -1]['Count'].tolist()
labels = topic_info[topic_info.Topic != -1]['Name'].tolist()


colors = ["#"+''.join([random.choice('0123456789ABCDEF') for j in range(6)])
          for i in range(len(topics))]

net = Network(height="700px", width="100%", notebook=True, cdn_resources='remote')


for i, t in enumerate(topics):

    top_words = topic_model.get_topic(t)
    top_words_str = ", ".join([w for w, _ in top_words[:10]])

    net.add_node(
        int(t),
        label=f"Topic {t}\n{labels[i]}",
        title=f"Documents: {sizes[i]}\nKeywords: {top_words_str}",
        size=10 + sizes[i]/50,
        color=colors[i],
    )


topic_texts = []
for t in topics:

    docs = topic_model.get_representative_docs(t)
    topic_texts.append(" ".join(docs[:20]))


vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(topic_texts)


sim_matrix = cosine_similarity(X)

threshold = 0.05
for i in range(len(topics)):
    for j in range(i+1, len(topics)):
        if sim_matrix[i, j] > threshold:
            net.add_edge(int(topics[i]), int(topics[j]), value=float(sim_matrix[i, j]))

html_file = "topic_network_colab.html"
net.show(html_file)

with open(html_file, 'r', encoding='utf-8') as f:
    html_content = f.read()
display(HTML(html_content))