# -*- coding: utf-8 -*-
"""load_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10jK1O6i-O7LZa8mBzkHSPAwpwtpFfufW
"""

!pip install -q gensim emoji contractions langdetect

import re
import string
import emoji
import contractions
from langdetect import detect, LangDetectException

# ── 0.1 Imports ─────────────────────────────────────────────────────────────
import os, sys, json, time, warnings, logging
import random
from pathlib import Path
from datetime import datetime
from collections import Counter

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.auto import tqdm

# Sklearn
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import (
    StratifiedKFold, train_test_split, cross_val_score
)
from sklearn.metrics import (
    classification_report, confusion_matrix,
    f1_score, accuracy_score, roc_auc_score
)
from sklearn.preprocessing import LabelEncoder
import joblib

# XGBoost
from xgboost import XGBClassifier

# Deep learning
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from torch.optim import AdamW
from torch.optim.lr_scheduler import ReduceLROnPlateau

# Transformers
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments, Trainer,
    EarlyStoppingCallback
)
from transformers.trainer_utils import get_last_checkpoint

# Embeddings
import gensim.downloader as api

# NLP
import nltk
import re, unicodedata
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
nltk.download(["stopwords", "wordnet", "punkt"], quiet=True)

warnings.filterwarnings("ignore")
logging.basicConfig(level=logging.INFO)
print("Imports OK")

def set_seed(seed: int = 42):
    """Fix all random seeds for full reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    os.environ["PYTHONHASHSEED"] = str(seed)

set_seed(CFG["seed"])
print("Seed set.")

# remove links , mentions and new line characters, emojis
# # Clean hashtags at the end of the sentence, and keep those in the middle of the sentence by removing just the # symbol
# Rimuove emoji
def strip_emoji(text):
    return emoji.replace_emoji(text, replace='')

# Rimuove punteggiatura, links, mentions, newline, ma mantiene stopwords
def strip_all_entities(text):
    text = re.sub(r'\r|\n', ' ', text.lower())  # lowercase + newline
    text = re.sub(r"(?:\@|https?\://)\S+", "", text)  # mentions e link
    text = re.sub(r'[^\x00-\x7f]', '', text)  # non-ASCII
    banned_list = string.punctuation
    table = str.maketrans('', '', banned_list)
    text = text.translate(table)
    return text

# Pulizia hashtag
def clean_hashtags(tweet):
    # Rimuove hashtag alla fine
    new_tweet = re.sub(r'(\s+#[[\w-]+)+s*$', '', tweet).strip()
    # Rimuove solo # all'interno della frase
    new_tweet = re.sub(r'#([\w-]+)', r'\1', new_tweet).strip()
    return new_tweet

# Filtra caratteri speciali come & e $
def filter_chars(text):
    return ' '.join('' if ('$' in word) or ('&' in word) else word for word in text.split())

# Rimuove spazi multipli
def remove_mult_spaces(text):
    return re.sub(r"\s\s+", " ", text)

# Tiene solo testi in inglese
def filter_non_english(text):
    try:
        lang = detect(text)
    except LangDetectException:
        lang = "unknown"
    return text if lang == "en" else ""

# Espande contrazioni
def expand_contractions(text):
    return contractions.fix(text)

# Rimuove numeri
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

# Rimuove parole troppo corte
def remove_short_words(text, min_len=2):
    words = text.split()
    long_words = [word for word in words if len(word) >= min_len]
    return ' '.join(long_words)

# Sostituisce parole allungate
def replace_elongated_words(text):
    regex_pattern = r'\b(\w+)((\w)\3{2,})(\w*)\b'
    return re.sub(regex_pattern, r'\1\3\4', text)

# Rimuove punteggiatura ripetuta
def remove_repeated_punctuation(text):
    return re.sub(r'[\?\.\!]+(?=[\?\.\!])', '', text)

# Rimuove spazi extra
def remove_extra_whitespace(text):
    return ' '.join(text.split())

# Rimuove short URLs comuni
def remove_url_shorteners(text):
    return re.sub(r'(?:http[s]?://)?(?:www\.)?(?:bit\.ly|goo\.gl|t\.co|tinyurl\.com|tr\.im|is\.gd|cli\.gs|u\.nu|url\.ie|tiny\.cc|alturl\.com|ow\.ly|bit\.do|adoro\.to)\S+', '', text)

# Strip spazi iniziali/finali
def remove_spaces_tweets(tweet):
    return tweet.strip()

# Rimuove tweet troppo corti (<3 parole)
def remove_short_tweets(tweet, min_words=3):
    words = tweet.split()
    return tweet if len(words) >= min_words else ""

# Funzione principale di cleaning
def clean_tweet(tweet):
    tweet = strip_emoji(tweet)
    tweet = expand_contractions(tweet)
    tweet = filter_non_english(tweet)
    tweet = strip_all_entities(tweet)
    tweet = clean_hashtags(tweet)
    tweet = filter_chars(tweet)
    tweet = remove_mult_spaces(tweet)
    tweet = remove_numbers(tweet)
    tweet = remove_short_words(tweet)
    tweet = replace_elongated_words(tweet)
    tweet = remove_repeated_punctuation(tweet)
    tweet = remove_extra_whitespace(tweet)
    tweet = remove_url_shorteners(tweet)
    tweet = remove_spaces_tweets(tweet)
    tweet = remove_short_tweets(tweet)
    tweet = ' '.join(tweet.split())  # rimuove eventuali spazi multipli residui
    return tweet

# ── 2.1 Preprocessing Functions ──────────────────────────────────────────────
STOP = set(stopwords.words("english"))  # [TASK-SPECIFIC] change language if needed
lemmatizer = WordNetLemmatizer()

def normalize_text(text: str) -> str:
    """
    Minimal cleaning — used as input for Transformers.
    Keeps punctuation and casing information the subword tokenizer relies on.
    """
    text = str(text).lower()
    text = unicodedata.normalize("NFKD", text)
    text = re.sub(r"http\S+|www\S+", " ", text)          # URLs
    text = re.sub(r"@\w+|#\w+", " ", text)                # mentions / hashtags
    text = re.sub(r"[^a-zA-Z0-9\s!?.,\'\']", " ", text)   # special chars
    text = re.sub(r"\s+", " ", text).strip()
    return text


def preprocess(text: str,
               remove_stopwords: bool = True,
               lemmatize: bool = True) -> str:
    """
    Full cleaning — used for classical ML and embedding-based models.
    Applies stopword removal and lemmatization on top of normalize_text.
    """
    text   = normalize_text(text)
    tokens = text.split()
    if remove_stopwords:
        tokens = [t for t in tokens if t not in STOP]
    if lemmatize:
        tokens = [lemmatizer.lemmatize(t) for t in tokens]
    return " ".join(tokens)


# Smoke test
sample = "This is a GREAT movie!! http://example.com @user #review"
print("Raw         :", sample)
print("Normalized  :", normalize_text(sample))
print("Preprocessed:", preprocess(sample))

# ── 4.1 Results Registry ─────────────────────────────────────────────────────
RESULTS = {}  # {"ModelName | split": {metric: value}}


# ── 4.2 Classification Evaluation ────────────────────────────────────────────
def evaluate_clf(model_name: str, y_true, y_pred,
                 y_prob=None, label_encoder=None, split: str = "test") -> dict:
    """
    Computes and prints classification metrics; stores them in RESULTS.

    Parameters
    ----------
    model_name    : display name for the model
    y_true        : ground-truth encoded labels
    y_pred        : predicted encoded labels
    y_prob        : class probabilities shape (n, 2) — binary tasks only, for ROC-AUC
    label_encoder : fitted sklearn LabelEncoder (for human-readable class names)
    split         : "val" or "test"

    Returns
    -------
    dict of computed metrics
    """
    acc       = accuracy_score(y_true, y_pred)
    f1_macro  = f1_score(y_true, y_pred, average="macro",    zero_division=0)
    f1_weight = f1_score(y_true, y_pred, average="weighted", zero_division=0)
    auc = (
        roc_auc_score(y_true, y_prob[:, 1])
        if (y_prob is not None and y_prob.shape[1] == 2) else None
    )

    print(f"\n{'='*55}")
    print(f"  {model_name} | {split.upper()}")
    print(f"{'='*55}")
    print(f"  Accuracy      : {acc:.4f}")
    print(f"  F1 (macro)    : {f1_macro:.4f}")
    print(f"  F1 (weighted) : {f1_weight:.4f}")
    if auc is not None:
        print(f"  ROC-AUC       : {auc:.4f}")

    class_names = label_encoder.classes_.tolist() if label_encoder else None
    print()
    print(classification_report(y_true, y_pred, target_names=class_names, zero_division=0))

    metrics = {"accuracy": acc, "f1_macro": f1_macro, "f1_weighted": f1_weight}
    if auc is not None:
        metrics["roc_auc"] = auc

    RESULTS[f"{model_name} | {split}"] = metrics
    return metrics


# ── 4.3 Confusion Matrix Plot ─────────────────────────────────────────────────
def plot_confusion_matrix_clf(y_true, y_pred, model_name: str, label_encoder=None):
    """
    Plots raw-count and row-normalised confusion matrices side by side.
    Saves figure to outputs/.
    """
    cm     = confusion_matrix(y_true, y_pred)
    labels = label_encoder.classes_ if label_encoder else np.unique(y_true)
    cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    for ax, data, title, fmt in zip(
        axes, [cm, cm_norm], ["Raw Counts", "Normalized"], ["d", ".2f"]
    ):
        sns.heatmap(data, annot=True, fmt=fmt, cmap="Blues",
                    xticklabels=labels, yticklabels=labels, ax=ax)
        ax.set_xlabel("Predicted")
        ax.set_ylabel("Actual")
        ax.set_title(title)

    plt.suptitle(f"Confusion Matrix — {model_name}", fontsize=13)
    plt.tight_layout()
    fname = CFG["output_dir"] / f"cm_{model_name.replace(' ', '_')}.png"
    plt.savefig(fname, dpi=120)
    plt.show()


# ── 4.4 Training History Plot ────────────────────────────────────────────────
def plot_history(history: dict, model_name: str):
    """
    Plots loss and F1-macro curves over epochs.

    Expected history keys:
        "train_loss"   : list[float]
        "val_loss"     : list[float]
        "val_f1_macro" : list[float]
    """
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    axes[0].plot(history["train_loss"], label="Train", marker="o")
    axes[0].plot(history["val_loss"],   label="Val",   marker="o")
    axes[0].set_title("Loss")
    axes[0].set_xlabel("Epoch")
    axes[0].legend()

    axes[1].plot(history["val_f1_macro"], marker="o", color="orange")
    axes[1].set_title("Val F1 Macro")
    axes[1].set_xlabel("Epoch")

    plt.suptitle(model_name, fontsize=13)
    plt.tight_layout()
    fname = CFG["output_dir"] / f"history_{model_name.replace(' ', '_')}.png"
    plt.savefig(fname, dpi=120)
    plt.show()


# ── 4.5 Results Summary Table ────────────────────────────────────────────────
def print_results_table():
    """Prints a formatted comparison table of all models stored in RESULTS."""
    if not RESULTS:
        print("RESULTS is empty — run evaluate_clf first.")
        return

    all_cols = sorted({k for v in RESULTS.values() for k in v.keys()})
    header = f"{'Model':<35}" + "".join(f"{c:>14}" for c in all_cols)
    sep = "=" * len(header)
    print(f"\n{sep}\n{header}\n{sep}")
    for name, metrics in RESULTS.items():
        row = f"{name:<35}" + "".join(
            f"{metrics.get(c, float('nan')):>14.4f}" for c in all_cols
        )
        print(row)
    print(sep)


print("Evaluation utilities ready.")