# -*- coding: utf-8 -*-
"""load_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfcB5TBdb1SqP2_TBCBk9hmsDraDUpPs

Drive link

https://drive.google.com/drive/folders/1MBQL_peAw52eJbv3OUykaU6SOosAtTgk
"""

import os
import shutil
from pathlib import Path
import joblib
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

# Dummy classes for demonstration (these would normally come from your_models.py)
class EmbeddingMLP(torch.nn.Module):
    def __init__(self, embedding_matrix, num_classes, hidden_dim, dropout):
        super().__init__()
        self.embedding = torch.nn.Embedding.from_pretrained(embedding_matrix, freeze=True)
        # Modified to match checkpoint's expected fc.0 and fc.3 structure
        self.fc = torch.nn.Sequential(
            torch.nn.Linear(embedding_matrix.shape[1], hidden_dim), # fc.0
            torch.nn.ReLU(),
            torch.nn.Dropout(dropout),
            torch.nn.Linear(hidden_dim, num_classes) # fc.3
        )

    def forward(self, x):
        # For this dummy, we assume input x is already an embedding or processed feature
        # If input were token IDs, you would process through self.embedding first.
        # Given the dummy_loader, x is treated as already-processed input for the MLP part.
        return self.fc(x)

class BiLSTMAttention(torch.nn.Module):
    def __init__(self, input_dim=50, hidden_dim=128, output_dim=3, n_layers=2, bidirectional=True, dropout=0.5):
        super().__init__()
        # Dummy implementation for now
        self.lstm = torch.nn.LSTM(input_dim, hidden_dim, num_layers=n_layers,
                                  bidirectional=bidirectional, dropout=dropout, batch_first=True)
        self.fc = torch.nn.Linear(hidden_dim * 2 if bidirectional else hidden_dim, output_dim)

    def forward(self, x):
        # For dummy, assume x is already embeddings of shape [batch_size, seq_len, input_dim]
        outputs, (hidden, cell) = self.lstm(x)
        # Simple pooling or use the last hidden state from BiLSTM
        hidden = torch.cat((hidden[-2,:,:], hidden[-1,:,:]), dim=1) if self.lstm.bidirectional else hidden[-1,:,:]
        return self.fc(hidden)

class TextCNN(torch.nn.Module):
    def __init__(self, vocab_size=10, embedding_dim=50, n_filters=100, filter_sizes=[3,4,5], output_dim=3, dropout=0.5):
        super().__init__()
        # Dummy implementation for now
        self.embedding = torch.nn.Embedding(vocab_size, embedding_dim)
        self.convs = torch.nn.ModuleList([
            torch.nn.Conv2d(in_channels=1, out_channels=n_filters, kernel_size=(fs, embedding_dim))
            for fs in filter_sizes
        ])
        self.fc = torch.nn.Linear(len(filter_sizes) * n_filters, output_dim)
        self.dropout = torch.nn.Dropout(dropout)

    def forward(self, x):
        # For dummy, assume x is token IDs of shape [batch_size, seq_len]
        embedded = self.embedding(x)
        embedded = embedded.unsqueeze(1) # [batch_size, 1, seq_len, embedding_dim]
        conved = [torch.nn.functional.relu(conv(embedded)).squeeze(3) for conv in self.convs]
        pooled = [torch.nn.functional.max_pool1d(conv, conv.shape[2]).squeeze(2) for conv in conved]
        cat = self.dropout(torch.cat(pooled, dim=1))
        return self.fc(cat)



# ─────────────── DRIVE SETUP ───────────────
def mount_drive():
    """
    Mount Google Drive if running on Colab.
    Returns the path to the models folder.
    """
    try:
        from google.colab import drive
        drive.mount('/content/drive', force_remount=False)
        drive_model_dir = Path("/content/drive/MyDrive/models")
        if not drive_model_dir.exists():
            raise FileNotFoundError(f"Models folder not found: {drive_model_dir}")
        print(f"Drive mounted. Models folder: {drive_model_dir}")
        return drive_model_dir
    except ImportError:
        # Not running on Colab; fallback to local folder
        drive_model_dir = Path("models")
        if not drive_model_dir.exists():
            raise FileNotFoundError(f"Models folder not found locally: {drive_model_dir}")
        print(f"Running locally. Models folder: {drive_model_dir}")
        return drive_model_dir

# Base path for all model files
DRIVE_MODEL_DIR = mount_drive()

# ─────────────── SCIKIT-LEARN / XGBOOST ───────────────
def load_logreg_model():
    """Load Logistic Regression model from Drive."""
    return joblib.load(DRIVE_MODEL_DIR / "logreg.pkl")

def load_xgboost_model():
    """Load XGBoost model from Drive."""
    return joblib.load(DRIVE_MODEL_DIR / "xgboost_gpu.pkl")

def predict_logreg(model, X):
    """Return predictions and probabilities for Logistic Regression."""
    return model.predict(X), model.predict_proba(X)

def predict_xgboost(model, X):
    """Return predictions and probabilities for XGBoost."""
    return model.predict(X), model.predict_proba(X)

# ─────────────── PYTORCH MODELS ───────────────
def load_mlp_model(model_class, embedding_matrix, num_classes, device=None):
    """
    Load MLP model with pre-trained weights.
    Returns model in eval mode and device used.
    """
    # from your_models import EmbeddingMLP # This line is no longer needed if classes are defined above
    device = device or ("cuda" if torch.cuda.is_available() else "cpu")
    model = model_class(embedding_matrix=embedding_matrix, num_classes=num_classes,
                        hidden_dim=256, dropout=0.3)
    model.load_state_dict(torch.load(DRIVE_MODEL_DIR / "mlp.pth", map_location=device))
    model.to(device).eval()
    return model, device

def load_bilstm_attention_model(device=None):
    """
    Load BiLSTM + Attention model from Drive.
    """
    # from your_models import BiLSTMAttention # This line is no longer needed if classes are defined above
    device = device or ("cuda" if torch.cuda.is_available() else "cpu")
    model = torch.load(DRIVE_MODEL_DIR / "bilstm_attention_full.pth", map_location=device)
    model.to(device).eval()
    return model, device

def load_textcnn_model(device=None):
    """
    Load TextCNN model from Drive.
    """
    # from your_models import TextCNN # This line is no longer needed if classes are defined above
    device = device or ("cuda" if torch.cuda.is_available() else "cpu")
    model = torch.load(DRIVE_MODEL_DIR / "textcnn_full.pth", map_location=device)
    model.to(device).eval()
    return model, device

def load_bilstm_model(device=None):
    """
    Load standard BiLSTM model from Drive.
    """
    # from your_models import BiLSTMAttention # This line is no longer needed if classes are defined above
    device = device or ("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
    model = torch.load(DRIVE_MODEL_DIR / "bilstm_full.pth", map_location=device)
    model.to(device).eval()
    return model, device

@torch.no_grad()
def infer_torch_model(model, dataloader, device):
    """
    Perform inference on a PyTorch model given a DataLoader.
    Returns predictions as a list of integers.
    """
    all_preds = []
    for batch in dataloader:
        inputs = batch["inputs"].to(device)
        outputs = model(inputs)
        preds = outputs.argmax(dim=1)
        all_preds.extend(preds.cpu().numpy())
    return all_preds

# ─────────────── TRANSFORMER HUGGING FACE ───────────────
def load_transformer_model(model_dir=None, device=None):
    """
    Load Transformer model + tokenizer from Drive using Hugging Face pipeline.
    Returns a ready-to-use text-classification pipeline.
    """
    device = device or ("cuda" if torch.cuda.is_available() else "cpu")
    model_dir = model_dir or DRIVE_MODEL_DIR / "transformer_best"

    # Load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(str(model_dir))
    model = AutoModelForSequenceClassification.from_pretrained(str(model_dir))

    # Create pipeline (device=0 for CUDA, -1 for CPU)
    pipe = pipeline("text-classification", model=model, tokenizer=tokenizer, device=0 if device=="cuda" else -1)
    return pipe

"""i try some inference to see if works



"""

# Dummy TF-IDF input (assumes X_test_tfidf already created)
# For demonstration, let's create a random sparse matrix
import numpy as np
from scipy.sparse import csr_matrix

# Load models first to get the expected number of features
logreg = load_logreg_model()
xgb = load_xgboost_model()

# Get the expected number of features from the loaded models
# For Logistic Regression, it's model.n_features_in_ attribute
n_features_expected = logreg.n_features_in_

# Example: 2 samples, with the correct number of features
X_test_tfidf = csr_matrix(np.random.rand(2, n_features_expected))


# Predict
logreg_preds, logreg_probs = logreg.predict(X_test_tfidf), logreg.predict_proba(X_test_tfidf)
xgb_preds, xgb_probs = xgb.predict(X_test_tfidf), xgb.predict_proba(X_test_tfidf)

print("LogReg predictions:", logreg_preds)
print("LogReg probabilities:", logreg_probs)
print("XGBoost predictions:", xgb_preds)
print("XGBoost probabilities:", xgb_probs)

# Dummy embedding matrix and labels
embedding_matrix = torch.rand(30000, 100)  # vocab_size=30000, embed_dim=100 as per error message
num_classes = 5 # Assuming 5 classes based on other models' output

# Load MLP
# The import from 'your_models' is now handled by the dummy class definition in the first cell.
mlp_model, device = load_mlp_model(EmbeddingMLP, embedding_matrix, num_classes)

# Dummy batch: 2 samples with 5 features each (simulate dataloader)
# The input size for MLP should match the embedding dimension or a processed embedding
dummy_loader = [{"inputs": torch.rand(2, embedding_matrix.shape[1]).to(device)}]

# Inference
preds = infer_torch_model(mlp_model, dummy_loader, device)
print("MLP predictions:", preds)

# Load Transformer pipeline
trf_pipe = load_transformer_model()

# Example sentences
sentences = ["This is a positive review!", "This is a negative review..."]
results = trf_pipe(sentences)

print("Transformer predictions:", results)